import { readSupabaseSchemaContract } from "../scripts/lib/supabase-migrations.mjs";
import { readFile } from "node:fs/promises";
import { readPlanningSurface } from "./helpers/planning-surface.mjs";
import test from "node:test";
import assert from "node:assert/strict";

test("fullscreen and planning panel use one task detail surface", async () => {
  const route = await readFile("src/app/tasks/[id]/page.tsx", "utf8");
  const detailDataRoute = await readFile("src/app/api/tasks/[id]/detail-data/route.ts", "utf8");
  const page = await readFile("src/features/tasks/templates/task-detail-page.tsx", "utf8");
  const panel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  const surface = await readFile("src/features/tasks/organisms/task-detail-surface.tsx", "utf8");
  const controller = await readFile("src/features/tasks/hooks/use-task-detail-controller.ts", "utf8");
  const panelHeader = await readFile("src/features/tasks/molecules/task-detail-panel-header.tsx", "utf8");
  const operationalHeader = await readFile("src/features/tasks/molecules/task-detail-operational-header.tsx", "utf8");
  const headerActions = await readFile("src/features/tasks/molecules/task-detail-header-actions.tsx", "utf8");
  const planningSection = await readFile("src/features/tasks/molecules/task-detail-planning-section.tsx", "utf8");
  const blockerSection = await readFile("src/features/tasks/molecules/task-detail-panel-blocker-section.tsx", "utf8");
  const overview = await readFile("src/features/tasks/organisms/task-overview-panel.tsx", "utf8");
  const workflowStrips = await readFile("src/features/tasks/molecules/task-detail-workflow-strips.tsx", "utf8");
  const tabs = await readFile("src/features/tasks/molecules/task-detail-tabs.tsx", "utf8");
  const ui = await readPlanningSurface();

  assert.match(route, /createSupabaseTaskDetailReadModel\(supabase\)\.load/);
  assert.doesNotMatch(route, /getPlanningShellState|loadTaskDetailData|mergeTaskDetailData/);
  assert.doesNotMatch(route, /SeedTaskDetailPage|source === "seed"/);
  assert.match(detailDataRoute, /\["ceo", "founder", "deputy", "viewer"\]/);
  assert.match(page, /TaskDetailSurface/);
  assert.match(page, /usePlanningAppController/);
  assert.match(page, /PlanningOverlayLayer/);
  assert.match(panel, /TaskDetailSurface/);
  assert.equal((page.match(/<TaskDetailSurface/g) || []).length, 1);
  assert.equal((panel.match(/<TaskDetailSurface/g) || []).length, 1);
  assert.match(panel, /role="dialog"/);
  assert.match(panel, /bg-slate-950\/25/);
  assert.match(panel, /<div ref=\{dialogRef\}/);
  assert.match(panel, /tabIndex=\{-1\}/);
  assert.match(panel, /onClick=\{requestClose\}/);
  assert.match(panel, /max-w-\[1060px\]/);
  assert.match(panel, /max-w-\[920px\]/);
  assert.match(panel, /absolute inset-y-0 right-0 z-10/);
  assert.match(panelHeader, /Große Ansicht/);
  assert.match(panelHeader, /href=\{`\/tasks\/\$\{task\.id\}`\}/);
  assert.match(surface, /TaskDetailOperationalHeader/);
  assert.match(surface, /const directChildType = task\.taskType === "epic"/);
  assert.match(surface, /TaskDetailTabs/);
  assert.match(surface, /TaskOverviewPanel/);
  assert.match(surface, /TaskRelationshipsSection/);
  assert.match(surface, /TaskDetailPanelChildrenSection/);
  assert.match(surface, /TaskDetailPanelBlockerSection/);
  assert.match(surface, /TaskDetailPlanningSection/);
  assert.match(surface, /TaskDetailWorkflowStrips/);
  assert.match(surface, /TaskDetailHeaderActions/);
  assert.doesNotMatch(surface, /Weitere Details/);
  assert.match(surface, /TaskCommentThread/);
  assert.match(operationalHeader, /Wartet auf/);
  assert.match(operationalHeader, /Andere warten hierauf/);
  assert.match(operationalHeader, /Accountable:/);
  assert.doesNotMatch(operationalHeader, /Parent:/);
  assert.match(overview, /sm:grid-cols-\[minmax\(0,1fr\)_auto\]/);
  assert.match(overview, /<LinkedPullRequestsSection compact/);
  assert.match(overview, /hasSubIssueBrief/);
  assert.match(overview, /Arbeitsbrief/);
  assert.match(overview, /weder Review, Score noch verpflichtende Nachweise/);
  assert.match(overview, /<ReadSection label="Zielbild" value=\{draft\.intendedOutcome\}/);
  assert.match(overview, /<ReadSection label="Abnahmekriterien" value=\{draft\.acceptanceCriteria\} checklist/);
  assert.match(overview, /<ReadSection label="Qualitätsstandard" value=\{draft\.definitionOfDone\} checklist/);
  assert.match(blockerSection, /embedded \? "shrink-0"/);
  assert.match(blockerSection, /embedded \? "Auswirkung auf die weitere Arbeit"/);
  assert.match(surface, /embedded=\{task\.taskType === "sub_issue"\}/);
  assert.match(headerActions, /GitHub Issue/);
  assert.match(headerActions, /Deliverable zurückziehen/);
  assert.match(planningSection, /Planung bearbeiten/);
  assert.match(workflowStrips, /Wartet auf Freigabe/);
  assert.match(tabs, /role="tablist"/);
  assert.match(tabs, /aria-selected/);
  assert.match(controller, /useTaskDetailController/);
  assert.match(controller, /saveOverview/);
  assert.match(controller, /taskOverviewPatch/);
  assert.match(controller, /overviewDirty/);
  assert.match(ui, /TaskDetailPanel/);
});

test("task detail loading avoids server waterfalls and defers inactive client features", async () => {
  const route = await readFile("src/app/tasks/[id]/page.tsx", "utf8");
  const overlays = await readFile("src/features/planning/organisms/planning-overlay-layer.tsx", "utf8");
  const tours = await readFile("src/features/product-tours/organisms/feature-tour-provider.tsx", "utf8");

  assert.match(route, /Promise\.all\(\[/);
  assert.match(route, /createSupabaseTaskDetailReadModel\(supabase\)\.load/);
  assert.match(route, /loadPlanningHeaderData\(supabase/);
  assert.doesNotMatch(route, /getPlanningShellState|taskDetailPageDataScope/);

  assert.match(overlays, /dynamic\(\s*\(\) =>\s*import\("@\/features\/planning\/organisms\/status-guard-dialog"\)/);
  assert.match(overlays, /dynamic\(\s*\(\) =>\s*import\("@\/features\/projects\/organisms\/initiative-dialog"\)/);
  assert.match(overlays, /dynamic\(\s*\(\) =>\s*import\("@\/features\/projects\/organisms\/milestone-dialog"\)/);
  assert.match(overlays, /dynamic\(\s*\(\) =>\s*import\("@\/features\/projects\/organisms\/milestone-delete-dialog"\)/);
  assert.match(overlays, /dynamic\(\s*\(\) =>\s*import\("@\/features\/tasks\/organisms\/new-task-dialog"\)/);
  assert.match(overlays, /dynamic\(\s*\(\) =>\s*import\("@\/features\/tasks\/organisms\/task-detail-panel"\)/);
  assert.doesNotMatch(overlays, /^import \{ (?:StatusGuardDialog|InitiativeDialog|NewTaskDialog|TaskDetailPanel) \}/m);
  assert.equal((overlays.match(/loading: \(\) => <OverlayLoadingFallback/g) || []).length, 6);
  assert.match(overlays, /role="status"/);
  assert.match(overlays, /aria-live="polite"/);
  assert.match(overlays, /Aufgabendetails werden geladen …/);

  assert.doesNotMatch(tours, /import \{ driver \} from "driver\.js"/);
  assert.match(tours, /const \{ driver \} = await import\("driver\.js"\)/);
  assert.ok(tours.indexOf("await waitForElement") < tours.indexOf('await import("driver.js")'));
  assert.match(tours, /Hilfe-Tour wird vorbereitet …/);
  assert.match(tours, /role=\{tourStatus\.kind === "error" \? "alert" : "status"\}/);
  assert.match(tours, /shouldReleaseFeatureTourClaim/);
});

test("shared task detail surface keeps github-like field saves and role gates", async () => {
  const surface = await readFile("src/features/tasks/organisms/task-detail-surface.tsx", "utf8");
  const operationalHeader = await readFile("src/features/tasks/molecules/task-detail-operational-header.tsx", "utf8");
  const headerActions = await readFile("src/features/tasks/molecules/task-detail-header-actions.tsx", "utf8");
  const planningSection = await readFile("src/features/tasks/molecules/task-detail-planning-section.tsx", "utf8");
  const workflowStrips = await readFile("src/features/tasks/molecules/task-detail-workflow-strips.tsx", "utf8");
  const overview = await readFile("src/features/tasks/organisms/task-overview-panel.tsx", "utf8");
  const permissions = await readFile("src/features/tasks/model/task-detail-permissions.ts", "utf8");
  const route = await readFile("src/features/planning-items/model/planning-items-browser-task-update.ts", "utf8");
  const routeHelpers = await readFile("src/features/tasks/model/task-route-update-helpers.ts", "utf8");

  assert.match(surface, /useTaskDetailController/);
  assert.match(surface, /overviewPermissions/);
  assert.match(overview, /permissions\.canEditBrief/);
  assert.match(overview, /permissions\.canEditEvidence/);
  assert.match(overview, /permission: "canEditNotes"/);
  assert.match(surface, /permissions\.canComment/);
  assert.match(headerActions, /Bearbeiten/);
  assert.match(overview, /Speichern/);
  assert.doesNotMatch(overview, /onBlur=/);
  assert.match(operationalHeader, /onUpdate\(\{ priority: value \}\)/);
  assert.match(planningSection, /onUpdate\(\{ sprintId \}\)/);
  assert.match(workflowStrips, /canManageReviewOwner/);
  assert.match(workflowStrips, /reviewOwnerProfileId/);
  assert.match(permissions, /taskOwnedByProfile/);
  assert.match(permissions, /role !== "viewer"/);
  assert.match(route, /taskDetailPermissions/);
  assert.match(routeHelpers, /founderOwnedTaskUpdateFields/);
});

test("planning hierarchy treats Sprint as a time container and strategic levels as planning items", async () => {
  const migration = await readSupabaseSchemaContract();
  const docs = await readFile("docs/planning-hierarchy.md", "utf8");
  const projectsPage = await readFile("src/app/(workspaces)/projects/page.tsx", "utf8");
  const backlogOverview = await readFile("src/features/backlog/organisms/backlog-overview.tsx", "utf8");
  const backlogTree = await readFile("src/features/backlog/molecules/planning-backlog-tree.tsx", "utf8");
  const planningLevel = await readFile("src/features/planning/model/planning-level.ts", "utf8");
  const planningFilters = await readFile("src/features/planning/organisms/planning-filters.tsx", "utf8");
  const board = await readFile("src/features/planning/organisms/planning-task-view-renderer.tsx", "utf8");

  assert.match(migration, /tasks_task_type_check[^]*task_type in \('epic', 'initiative', 'deliverable', 'sub_issue'\)/);
  assert.match(migration, /create table if not exists public\.planning_item_strategy/);
  assert.match(migration, /create table if not exists public\.planning_item_raci_assignments/);
  assert.match(migration, /create table if not exists public\.planning_item_legacy_ids/);
  assert.match(migration, /planning_item_raci_one_accountable_idx/);
  assert.match(migration, /tasks_planning_parent_type_status_sort_idx/);
  assert.match(docs, /Epic[\s\S]*Initiative[\s\S]*Deliverable[\s\S]*Sub-Issue/);
  assert.match(docs, /Sprint is a time container, never a hierarchy parent/);
  assert.match(docs, /GitHub projection is available only for Deliverables and Sub-Issues/);
  assert.match(projectsPage, /redirect\("\/backlog\?backlog\.level=epic"\)/);
  assert.match(backlogOverview, /Planungsebene im Backlog/);
  assert.match(planningLevel, /value: "epic", label: "Epics"/);
  assert.match(planningLevel, /value: "initiative", label: "Initiativen"/);
  assert.match(planningLevel, /value: "deliverable", label: "Deliverables"/);
  assert.match(backlogOverview, /PlanningBacklogTree/);
  assert.match(backlogTree, /BacklogPlanningLevel = PlanningLevel/);
  assert.match(backlogTree, /Der Pfeil öffnet nur direkte Kinder/);
  assert.match(backlogTree, /Ohne Epic/);
  assert.match(backlogTree, /Ohne Initiative/);
  assert.match(backlogTree, /collapsedGroups/);
  assert.match(backlogTree, /aria-expanded=\{!collapsed\}/);
  assert.match(backlogTree, /hidden=\{collapsed\}/);
  assert.match(backlogTree, /const rollup = taskChildProgress\(rollupTasks\)/);
  assert.match(backlogTree, /label=\{rollupLabel\}/);
  assert.match(planningFilters, /Parent-Epic/);
  assert.match(planningFilters, /Parent-Initiative/);
  assert.match(board, /planningLevel/);
});

test("management repo cleanup plan protects legacy templates from deletion without approval", async () => {
  const plan = await readFile("docs/management-repo-v2-plan.md", "utf8");
  const deliverableTemplate = await readFile("docs/management-templates-v2/deliverable.yml", "utf8");
  const groupTemplate = await readFile("docs/management-templates-v2/initiative.yml", "utf8");
  const subIssueTemplate = await readFile("docs/management-templates-v2/sub-issue.yml", "utf8");

  assert.match(plan, /Keine Datei im Management-Repo löschen/);
  assert.match(plan, /Erst archivieren statt endgültig löschen/);
  assert.match(plan, /auto-triage\.yml/);
  assert.match(plan, /sprint-title-sync\.yml/);
  assert.match(deliverableTemplate, /GitHub ist Backup, nicht Quelle der Wahrheit/);
  assert.match(deliverableTemplate, /Acceptance Criteria/);
  assert.match(groupTemplate, /Epic \/ Meilenstein/);
  assert.match(subIssueTemplate, /nicht score-relevant/);
});
