import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { readFeatureSurface, readPlanningSurface } from "./helpers/planning-surface.mjs";
import test from "node:test";
import assert from "node:assert/strict";

test("platform migration contains the role, score and sync contracts", async () => {
  const sql = await readFile("supabase/0002_founder_platform.sql", "utf8");
  const cleanup = await readFile("supabase/0038_remove_meeting_finder_decision_log.sql", "utf8");

  assert.match(sql, /platform_role text/);
  assert.match(sql, /github_login text unique/);
  assert.match(sql, /audit_log/);
  assert.match(sql, /review_status/);
  assert.match(sql, /github_sync_status/);
  assert.match(sql, /current_platform_role/);
  assert.match(cleanup, /drop table if exists decision_log cascade/);
  assert.match(cleanup, /drop table if exists availability cascade/);
});

test("github sync route is team-scoped and locked per github resource", async () => {
  const route = await readFile("src/app/api/tasks/[id]/sync-github/route.ts", "utf8");
  const githubApp = await readFile("src/lib/github-app.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");
  const migration = await readFile("supabase/0038_github_sync_locks.sql", "utf8");
  const transactionalSyncMigration = await readFile("supabase/0047_transactional_task_creation_and_github_sync.sql", "utf8");
  const schemaChecks = await readFile("src/lib/planning-schema-checks.json", "utf8");
  const syncHook = await readFile("src/features/tasks/hooks/use-task-github-sync-command.ts", "utf8");
  const verifySupabase = await readFile("scripts/verify-supabase.mjs", "utf8");

  assert.match(route, /requireTeamMember/);
  assert.match(route, /getGitHubAppConnectionStatus/);
  assert.match(route, /getGitHubAppInstallationToken/);
  assert.match(route, /githubInstallationToken/);
  assert.match(route, /syncGitHubIssueDependencies/);
  assert.match(route, /githubDependencyContext/);
  assert.match(route, /githubSyncResourceKey/);
  assert.match(route, /acquireGitHubSyncLock/);
  assert.match(route, /releaseGitHubSyncLock/);
  assert.match(route, /finally/);
  assert.match(route, /github_sync_locked/);
  assert.match(route, /GitHub-Sync läuft bereits/);
  assert.match(githubApp, /GITHUB_APP_INSTALLATION_ID/);
  assert.match(githubApp, /cachedInstallationToken/);
  assert.match(migration, /create table if not exists github_issue_sync_locks/);
  assert.match(migration, /try_acquire_github_issue_sync_lock/);
  assert.match(migration, /release_github_issue_sync_lock/);
  assert.match(migration, /on conflict \(resource_key\) do update/);
  assert.match(migration, /expires_at <= now\(\)/);
  assert.match(schemaChecks, /github_issue_sync_locks/);
  assert.match(verifySupabase, /verifyGitHubSyncLockRpc/);
  assert.match(verifySupabase, /active lock was acquired twice/);
  assert.match(syncHook, /onlyFailed/);
  assert.match(syncHook, /continue;/);
  assert.doesNotMatch(route, /buildSyncContext/);
  assert.doesNotMatch(route, /x-github-provider-token|provider_token|requireMatchingGitHubProviderToken/);
  assert.doesNotMatch(route, /requireOperationalLead/);
  assert.doesNotMatch(route, /task_comments/);
  assert.doesNotMatch(route, /task_blockers/);
  assert.doesNotMatch(route, /from\("task_activity"\)\.select/);
  assert.doesNotMatch(route, /parent_task_id/);
  assert.match(route, /\.in\("relation_type", \["blocked_by", "blocks"\]\)/);
  assert.match(route, /createIfMissing/);
  assert.match(route, /Diese Aufgabe hat noch kein GitHub Issue/);
  assert.match(route, /Nur Deliverables können als GitHub Issue angelegt werden/);
  assert.match(route, /begin_github_issue_sync_transaction/);
  assert.match(route, /finalize_github_issue_sync_transaction/);
  assert.match(route, /fail_github_issue_sync_transaction/);
  assert.match(transactionalSyncMigration, /github_sync_status = 'pending'/);
  assert.match(transactionalSyncMigration, /github_sync_status = 'synced'/);
  assert.match(transactionalSyncMigration, /github_sync_status = 'failed'/);
  assert.match(github, /state: task\.status === "Erledigt" \? "closed" : "open"/);
  assert.match(github, /taskIssueMarker/);
  assert.match(github, /findGitHubIssueByTaskMarker/);
  assert.match(github, /founderops-task-id:/);
  assert.match(github, /recovered: true/);
});

test("operational leads can delete test tasks and close linked github issues", async () => {
  const taskRoute = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const taskApiClient = await readFile("src/features/tasks/model/task-api-client.ts", "utf8");
  const taskDeleteCommand = await readFile("src/features/tasks/hooks/use-task-delete-command.ts", "utf8");
  const deletionMigration = await readFile("supabase/0046_transactional_task_deletion.sql", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");
  const panelSidebar = await readFile("src/features/tasks/organisms/task-detail-panel-sidebar.tsx", "utf8");

  assert.match(taskRoute, /export async function DELETE/);
  assert.match(taskRoute, /Nur CEO oder Deputy können Aufgaben löschen/);
  assert.match(taskRoute, /archiveGitHubIssue/);
  assert.match(taskRoute, /githubClosed/);
  assert.match(taskRoute, /prepare_task_deletion_transaction/);
  assert.match(taskRoute, /finalize_task_deletion_transaction/);
  assert.match(taskRoute, /cancel_task_deletion_transaction/);
  assert.match(taskRoute, /prepared\.tasks \|\| \[prepared\.task\]/);
  assert.match(taskRoute, /for \(const issueNumber of issueNumbers\)/);
  assert.doesNotMatch(taskRoute, /from\("tasks"\)\.delete\(\)/);
  assert.match(taskApiClient, /json: \{ expectedUpdatedAt \}/);
  assert.match(taskDeleteCommand, /removeTaskTreeFromPlanningData/);
  assert.match(taskDeleteCommand, /restoreTaskTreeToPlanningData/);
  assert.match(deletionMigration, /create table if not exists public\.task_deletion_operations/);
  assert.match(deletionMigration, /delete from public\.tasks where id = v_operation\.task_id/);
  assert.match(deletionMigration, /insert into public\.audit_log/);
  assert.match(deletionMigration, /status = 'completed'/);
  assert.match(deletionMigration, /revoke all on function public\.prepare_task_deletion_transaction/);
  assert.match(github, /export async function archiveGitHubIssue/);
  assert.match(github, /state_reason: "not_planned"/);
  assert.match(github, /test\/deleted/);
  assert.match(panelSidebar, /Test & Bereinigung/);
  assert.match(panelSidebar, /Aufgabe löschen/);
});

test("github issue export includes only the task brief and FounderOps source", async () => {
  const github = await readFile("src/lib/github.ts", "utf8");
  const ui = await readPlanningSurface();
  const panelSidebar = await readFile("src/features/tasks/organisms/task-detail-panel-sidebar.tsx", "utf8");
  const notificationsOverviewUi = await readFile("src/features/notifications/organisms/notifications-overview.tsx", "utf8");
  const platform = await readFile("src/lib/platform.ts", "utf8");

  assert.match(github, /taskIssueTitle/);
  assert.match(github, /taskIssueLabels/);
  assert.match(github, /task\.taskType === "deliverable" \? "deliverable"/);
  assert.match(github, /review:ready/);
  assert.match(github, /Problem Statement/);
  assert.match(github, /Intended Outcome/);
  assert.match(github, /Scope & Constraints/);
  assert.match(github, /Acceptance Criteria/);
  assert.match(github, /Evidence Required/);
  assert.match(github, /Definition of Done/);
  assert.match(github, /Open in FounderOps/);
  assert.match(github, /APP_URL/);
  assert.match(github, /\/tasks\/\$\{encodeURIComponent\(taskId\)\}/);
  assert.match(github, /Planning context:/);
  assert.match(github, /GitHub issue sync keeps the working issue aligned/);
  assert.match(github, /syncGitHubIssueDependencies/);
  assert.match(github, /dependencies\/blocked_by/);
  assert.doesNotMatch(github, /Score-relevant/);
  assert.doesNotMatch(github, /Offene Blocker/);
  assert.doesNotMatch(github, /Relationships/);
  assert.doesNotMatch(github, /Letzte Kommentare/);
  assert.doesNotMatch(github, /Aktivitätsprotokoll/);
  assert.doesNotMatch(github, /Planning Metadata/);
  assert.doesNotMatch(github, /Founder Scoreboard v2 Task ID/);
  assert.doesNotMatch(github, /Sync-Ziel/);
  assert.doesNotMatch(github, /Bestehendes GitHub Issue/);
  assert.match(github, /task\.issueNumber/);
  assert.match(platform, /hasGitHubIssue/);
  assert.match(ui, /syncTaskToGitHub/);
  assert.match(panelSidebar, /GitHub Issue/);
  assert.match(panelSidebar, /Sync/);
  assert.match(ui, /NotificationsOverview/);
  assert.doesNotMatch(notificationsOverviewUi, /GitHubSyncQueueSection/);
  assert.doesNotMatch(notificationsOverviewUi, /SystemStatusSection|settings-readiness/);
  assert.match(ui, /createIfMissing: false/);
});

test("task relationships use github-like blocked by and blocking semantics", async () => {
  const migration = await readFile("supabase/0016_task_relationship_edges.sql", "utf8");
  const route = await readFile("src/app/api/tasks/[id]/relationships/route.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");
  const data = await readFile("src/lib/planning-data-loader.ts", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");
  const platform = await readFile("src/lib/platform.ts", "utf8");
  const display = await readFile("src/lib/display.ts", "utf8");
  const panel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  const relationshipUi = await readFile("src/features/tasks/molecules/relationship-list.tsx", "utf8");
  const detail = await readFile("src/features/tasks/templates/task-detail-page.tsx", "utf8");
  const taskDetailWorkflow = await readFile("src/features/tasks/hooks/use-task-detail-workflow.ts", "utf8");
  const relationshipHook = await readFile("src/features/tasks/hooks/use-task-relationships.ts", "utf8");
  const relationshipSection = await readFile("src/features/tasks/organisms/task-relationships-section.tsx", "utf8");
  const taskApiClient = await readFile("src/features/tasks/model/task-api-client.ts", "utf8");
  const relationshipViewModel = await readFile("src/lib/relationship-view-model.ts", "utf8");
  const script = await readFile("scripts/migrate-task-relationships.mjs", "utf8");

  assert.match(migration, /create table if not exists task_relationship_edges/);
  assert.match(migration, /blocked_by/);
  assert.match(migration, /blocks/);
  assert.match(migration, /relates_to/);
  assert.match(route, /requireOperationalLead/);
  assert.match(route, /task.relationship_created/);
  assert.match(route, /task.relationship_deleted/);
  assert.match(route, /github_sync_status: "not_synced"/);
  assert.match(types, /TaskRelationType/);
  assert.match(data, /task_relationship_edges/);
  assert.match(platform, /taskRelationsFor/);
  assert.match(platform, /hasOpenWaitingRelation/);
  assert.match(platform, /blockingTask && blockingTask\.status !== "Erledigt"/);
  assert.match(display, /Diese Aufgabe kann erst sauber weitergehen/);
  assert.match(display, /Verknüpft mit/);
  assert.match(relationshipViewModel, /relationshipBadgeFor/);
  assert.match(relationshipViewModel, /Blockiert aktuell/);
  assert.match(relationshipViewModel, /Blocker erledigt/);
  assert.match(relationshipViewModel, /Blockiert andere/);
  assert.match(relationshipViewModel, /Abhängigkeit erfüllt/);
  assert.match(relationshipViewModel, /Verknüpft/);
  assert.match(relationshipViewModel, /relationMatchesDraft/);
  const panelDependencies = await readFile("src/features/tasks/molecules/task-detail-panel-dependencies-section.tsx", "utf8");
  const relationshipForm = await readFile("src/features/tasks/molecules/task-relationship-form.tsx", "utf8");
  const panelRelationshipContract = `${panelDependencies}\n${relationshipForm}`;
  assert.match(panelRelationshipContract, /Abhängigkeit hinzufügen/);
  assert.match(panelRelationshipContract, /Abhängigkeit existiert bereits/);
  assert.match(panelRelationshipContract, /Diese Abhängigkeit ist bereits gespeichert/);
  assert.match(panelDependencies, /relationMatchesDraft/);
  assert.match(detail, /useTaskDetailWorkflow/);
  assert.match(taskDetailWorkflow, /useTaskRelationships/);
  assert.match(detail, /task=\{task\}/);
  assert.match(relationshipHook, /Abhängigkeit konnte nicht gespeichert werden/);
  assert.match(relationshipHook, /Abhängigkeit konnte nicht entfernt werden/);
  assert.match(taskApiClient, /api\/tasks\/\$\{taskId\}\/relationships/);
  assert.match(taskApiClient, /method: "POST"/);
  assert.match(taskApiClient, /method: "DELETE"/);
  assert.match(relationshipHook, /setRelations\(\(current\) => \[localRelation, \.\.\.current\]\)/);
  assert.match(panel, /TaskDetailPanelDependenciesSection/);
  assert.match(panelDependencies, /RelationshipList/);
  assert.match(panelDependencies, /Wartet auf/);
  assert.match(relationshipUi, /relationshipHelpText/);
  assert.match(relationshipUi, /relationshipBadgeFor/);
  assert.match(relationshipUi, /relationshipBadgeToneClass/);
  assert.match(detail, /TaskRelationshipsSection/);
  assert.match(relationshipSection, /RelationshipList/);
  assert.match(`${relationshipSection}\n${relationshipForm}`, /Abhängigkeit hinzufügen/);
  assert.match(`${relationshipSection}\n${relationshipForm}`, /Abhängigkeit existiert bereits/);
  assert.doesNotMatch(relationshipSection, /RelationshipPanelList/);
  assert.match(github, /blockedIssueNumber/);
  assert.match(github, /blockingIssueNumber/);
  assert.match(github, /desiredByBlocked/);
  assert.match(github, /removeGitHubIssueBlockedBy/);
  assert.match(github, /issueDependencyGitHubApiVersion = "2026-03-10"/);
  assert.match(script, /task_dependencies/);
  assert.match(script, /relation_type: "blocked_by"/);
});

test("github sync queue is reopened by task comments blockers and relationship changes", async () => {
  const taskRoute = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const taskRouteHelpers = await readFile("src/features/tasks/model/task-route-update-helpers.ts", "utf8");
  const taskRoutePolicy = `${taskRoute}\n${taskRouteHelpers}`;
  const commentsRoute = await readFile("src/app/api/tasks/[id]/comments/route.ts", "utf8");
  const blockersRoute = await readFile("src/app/api/tasks/[id]/blockers/route.ts", "utf8");
  const relationshipsRoute = await readFile("src/app/api/tasks/[id]/relationships/route.ts", "utf8");
  const syncRoute = await readFile("src/app/api/tasks/[id]/sync-github/route.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");

  assert.match(taskRoutePolicy, /payload\.githubSyncStatus === undefined/);
  assert.match(taskRoutePolicy, /github_sync_status = "not_synced"/);
  assert.match(commentsRoute, /github_sync_status: githubSyncError \? "failed" : "not_synced"/);
  assert.match(commentsRoute, /github_sync_error: githubSyncError \|\| null/);
  assert.match(blockersRoute, /github_sync_status: "not_synced"/);
  assert.match(relationshipsRoute, /github_sync_status: "not_synced"/);
  assert.match(syncRoute, /task_relationship_edges/);
  assert.match(syncRoute, /syncGitHubIssueDependencies/);
  assert.match(syncRoute, /\.in\("relation_type", \["blocked_by", "blocks"\]\)/);
  assert.doesNotMatch(syncRoute, /activitiesResult/);
  assert.doesNotMatch(syncRoute, /profileNameById\.get\(relation\.task\?\.owner/);
  assert.match(github, /Problem Statement/);
  assert.doesNotMatch(github, /Review fällig bis/);
  assert.doesNotMatch(github, /Priorität/);
  assert.doesNotMatch(github, /Verknüpft mit/);
});

test("github sync maps the visible task assignee to native github assignees", async () => {
  const syncRoute = await readFile("src/app/api/tasks/[id]/sync-github/route.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");
  const migration = await readFile("supabase/0047_transactional_task_creation_and_github_sync.sql", "utf8");

  assert.match(syncRoute, /profiles"\)\.select\("id,name,github_login"\)/);
  assert.match(syncRoute, /profileGitHubLoginById/);
  assert.match(syncRoute, /const assigneeProfileId = data\.assignee \|\| ""/);
  assert.match(syncRoute, /upsertGitHubIssue\(task, githubInstallationToken, \{ login: assigneeLogin \}\)/);
  assert.match(syncRoute, /const warnings = issue\.warnings \|\| \[\]/);
  assert.match(syncRoute, /Warnung:/);
  assert.match(syncRoute, /finalize_github_issue_sync_transaction/);
  assert.match(migration, /github_sync_status = 'synced'/);
  assert.match(migration, /github_sync_error = null/);
  assert.match(syncRoute, /warnings/);
  assert.doesNotMatch(syncRoute, /review_owner_profile_id/);
  assert.doesNotMatch(syncRoute, /packages"\)/);

  assert.match(github, /GitHubIssueAssigneeInput/);
  assert.match(github, /repos\/\$\{owner\}\/\$\{repo\}\/assignees\/\$\{encodeURIComponent\(login\)\}/);
  assert.match(github, /response\.status === 204/);
  assert.match(github, /response\.status === 404/);
  assert.match(github, /payload\.assignees = \[assigneeLogin\]/);
  assert.match(github, /GitHub-Assignee @\$\{assigneeLogin\} ist im Repository nicht zuweisbar/);
  assert.match(github, /GitHub-Assignee nicht gesetzt/);
  assert.match(github, /labels: taskIssueLabels\(task\)/);
  assert.doesNotMatch(github, /owner:assignee|assignee:owner|review-owner|initiative-owner/i);
});

test("github sync verification is read-only and checks the management repo", async () => {
  const script = await readFile("scripts/verify-github-sync.mjs", "utf8");
  const pkg = await readFile("package.json", "utf8");

  assert.match(pkg, /verify:github-sync/);
  assert.match(script, /github_app_installation_token/);
  assert.match(script, /GITHUB_SYNC_OWNER/);
  assert.match(script, /GITHUB_SYNC_REPO/);
  assert.match(script, /linkedDeliverables\.filter/);
  assert.match(script, /automaticSyncScope/);
  assert.match(script, /syncQueuePreview/);
  assert.match(script, /appOnlyPreview/);
  assert.doesNotMatch(script, /method: "POST"/);
  assert.doesNotMatch(script, /method: "PATCH"/);
  assert.doesNotMatch(script, /method: "DELETE"/);
});

test("app-only tasks are visibly marked without creating github issues", async () => {
  const ui = await readPlanningSurface();
  const panel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  const panelSidebar = await readFile("src/features/tasks/organisms/task-detail-panel-sidebar.tsx", "utf8");
  const notificationsOverviewUi = await readFile("src/features/notifications/organisms/notifications-overview.tsx", "utf8");
  const taskCard = await readFile("src/features/tasks/molecules/task-card.tsx", "utf8");
  const detail = await readFile("src/features/tasks/templates/task-detail-page.tsx", "utf8");
  const detailGitHubSyncCard = await readFile("src/features/tasks/molecules/task-github-sync-card.tsx", "utf8");
  const queue = await readFile("src/features/tasks/organisms/task-github-sync-queue.tsx", "utf8");

  assert.match(ui, /GitHubMissingBadge/);
  assert.match(ui, /TaskGitHubSyncQueue/);
  assert.match(taskCard, /Kein Issue/);
  assert.match(taskCard, /GitHub offen/);
  assert.match(taskCard, /Sync läuft/);
  assert.match(taskCard, /Sync fehlgeschlagen/);
  assert.doesNotMatch(notificationsOverviewUi, /task\.taskType === "deliverable"/);
  assert.doesNotMatch(notificationsOverviewUi, /Extern anlegen|Keine Aufgaben ohne externe Ablage/);
  assert.match(queue, /GitHub Issue anlegen/);
  assert.match(queue, /Offene Issues syncen/);
  assert.match(queue, /onlyFailed: true/);
  assert.match(queue, /Sync läuft bereits/);
  assert.match(panel, /TaskDetailPanelSidebar/);
  assert.match(panelSidebar, /GitHub Issue anlegen/);
  assert.match(ui, /createIfMissing: true/);
  assert.doesNotMatch(notificationsOverviewUi, /onCreateGitHubIssue/);
  assert.match(detailGitHubSyncCard, /Noch kein GitHub Issue/);
  assert.match(detailGitHubSyncCard, /GitHub Issue anlegen/);
  assert.match(detail, /createIfMissing: true/);
  assert.match(detail, /githubState/);
  assert.match(panelSidebar, /GitHub Issue nur bewusst anlegen/);
  assert.match(detailGitHubSyncCard, /GitHub Issue nur bewusst anlegen/);
});

test("existing management issues are linked before creating duplicates", async () => {
  const script = await readFile("scripts/plan-github-issue-linking.mjs", "utf8");
  const docs = await readFile("docs/planning-hierarchy.md", "utf8");

  assert.match(script, /normalizeTitle/);
  assert.match(script, /exactMatches/);
  assert.match(script, /ambiguousMatches/);
  assert.match(script, /github_issue_number/);
  assert.match(script, /--apply/);
  assert.match(docs, /Bestehende GitHub-Issues/);
  assert.match(docs, /nicht gelöscht und nicht dupliziert/);
});

test("legacy github body sections are not kept inside evidence link fields", async () => {
  const repairScript = await readFile("scripts/repair-evidence-link-sections.mjs", "utf8");
  const githubCommentsRoute = await readFile("src/app/api/tasks/[id]/github-comments/route.ts", "utf8");

  assert.match(repairScript, /cleanEvidenceLinkValue/);
  assert.match(repairScript, /Non-Tech Summary/);
  assert.match(repairScript, /Follow-up Issues/);
  assert.match(repairScript, /No response/);
  assert.match(repairScript, /evidence_link/);
  assert.match(repairScript, /--apply/);
  assert.match(repairScript, /github_sync_status = "not_synced"|github_sync_status: "not_synced"/);
  assert.match(githubCommentsRoute, /extractEvidenceFromIssueBody/);
});

test("github app connect persists reload-stable user tokens without browser token headers", async () => {
  const ui = await readPlanningSurface();
  const requestContext = await readFile("src/features/planning/hooks/use-planning-request-context.ts", "utf8");
  const browserApiClient = await readFile("src/lib/browser-api-client.ts", "utf8");
  const authHook = await readFile("src/features/planning/hooks/use-planning-auth.ts", "utf8");
  const connectionModel = await readFile("src/features/planning/model/github-app-connection.ts", "utf8");
  const notificationsOverviewUi = await readFile("src/features/notifications/organisms/notifications-overview.tsx", "utf8");
  const detail = await readFile("src/features/tasks/templates/task-detail-page.tsx", "utf8");
  const taskDetailWorkflow = await readFile("src/features/tasks/hooks/use-task-detail-workflow.ts", "utf8");
  const detailGitHubSyncCard = await readFile("src/features/tasks/molecules/task-github-sync-card.tsx", "utf8");
  const planningShell = await readFile("src/features/planning/templates/planning-app-shell.tsx", "utf8");
  const githubStatus = await readFile("src/features/planning/molecules/github-connection-status.tsx", "utf8");
  const planningHeader = await readFile("src/features/planning/organisms/planning-header.tsx", "utf8");
  const thread = await readFile("src/features/tasks/organisms/task-comment-thread.tsx", "utf8");
  const commentHook = await readFile("src/features/tasks/hooks/use-task-comments.ts", "utf8");
  const collaborationHook = await readFile("src/features/tasks/hooks/use-task-collaboration-commands.ts", "utf8");
  const taskApiClient = await readFile("src/features/tasks/model/task-api-client.ts", "utf8");
  const commentBody = await readFile("src/features/tasks/atoms/task-comment-body.tsx", "utf8");
  const commentComposer = await readFile("src/features/tasks/molecules/task-comment-composer.tsx", "utf8");
  const githubCommentImage = await readFile("src/features/tasks/molecules/github-comment-image.tsx", "utf8");
  const githubApp = await readFile("src/lib/github-app.ts", "utf8");
  const githubAppMigration = await readFile("supabase/0036_github_app_user_tokens.sql", "utf8");
  const connectRoute = await readFile("src/app/api/github-app/connect/route.ts", "utf8");
  const appCallbackRoute = await readFile("src/app/api/github-app/callback/route.ts", "utf8");
  const appStatusRoute = await readFile("src/app/api/github-app/status/route.ts", "utf8");
  const appConnectionRoute = await readFile("src/app/api/github-app/connection/route.ts", "utf8");
  const supabase = await readFile("src/lib/supabase.ts", "utf8");
  const serverSupabase = await readFile("src/lib/supabase-server.ts", "utf8");
  const proxy = await readFile("src/proxy.ts", "utf8");
  const callback = await readFile("src/app/auth/callback/route.ts", "utf8");
  const syncRoute = await readFile("src/app/api/tasks/[id]/sync-github/route.ts", "utf8");
  const commentsRoute = await readFile("src/app/api/tasks/[id]/comments/route.ts", "utf8");
  const attachmentRoute = await readFile("src/app/api/tasks/[id]/attachments/route.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");
  const authDocs = await readFile("docs/auth-flow.md", "utf8");
  const rules = await readFile("AGENTS.md", "utf8");

  assert.match(ui, /usePlanningAuth/);
  assert.match(authHook, /signInWithOAuth/);
  assert.match(authHook, /scopes: "repo read:user user:email"/);
  assert.match(authHook, /\/api\/github-app\/status/);
  assert.match(authHook, /\/api\/github-app\/connect\?next=/);
  assert.match(authHook, /githubAppConnected/);
  assert.match(authHook, /githubConnectionState/);
  assert.match(connectionModel, /"checking" \| "connected" \| "missing" \| "reconnect_required" \| "unknown"/);
  assert.match(connectionModel, /githubAppConnectionStateFromStatus/);
  assert.match(authHook, /setGithubConnectionState\("checking"\)/);
  assert.match(authHook, /githubAppConnectionStateFromStatus\(status\)/);
  assert.doesNotMatch(authHook, /provider_token|markGitHubReauthAttempt|clearRememberedGitHubProviderToken|sessionStorage/);
  assert.match(requestContext, /createBrowserApiClient/);
  assert.match(browserApiClient, /\/api\/github-app\/status/);
  assert.match(browserApiClient, /startGitHubAppConnect/);
  assert.match(browserApiClient, /githubAppConnected/);
  assert.doesNotMatch(browserApiClient, /x-github-provider-token|getRememberedGitHubProviderToken|rememberGitHubProviderToken|includeGitHubToken|provider_token/);
  assert.doesNotMatch(detail, /x-github-provider-token|getRememberedGitHubProviderToken|getBrowserSupabase|auth\.getSession/);
  assert.match(supabase, /createBrowserClient/);
  assert.match(supabase, /browserSupabaseUrl && browserSupabaseAnonKey/);
  assert.match(supabase, /persistSession: true/);
  assert.match(supabase, /autoRefreshToken: true/);
  assert.match(serverSupabase, /createServerClient/);
  assert.match(proxy, /supabase\.auth\.getUser\(\)/);
  assert.match(callback, /exchangeCodeForSession\(code\)/);
  assert.match(authHook, /refreshSessionState/);
  assert.match(authHook, /supabase\.auth\.refreshSession\(\)/);
  assert.match(authHook, /visibilitychange/);
  assert.match(authHook, /5 \* 60 \* 1000/);
  assert.doesNotMatch(planningHeader, /markGitHubReauthAttempt|hasGitHubReauthAttempt/);
  assert.match(detail, /useTaskDetailWorkflow/);
  assert.match(taskDetailWorkflow, /createBrowserApiClient/);
  assert.match(taskDetailWorkflow, /startGitHubAppConnect/);
  assert.match(ui, /GitHubConnectionStatus/);
  assert.doesNotMatch(ui, /GitHubAppReconnectBanner/);
  assert.match(detail, /GitHubConnectionStatus/);
  assert.match(planningShell, /<PlanningHeader controller=\{controller\} \/>/);
  assert.doesNotMatch(planningShell, /GitHubAppReconnectBanner|githubAppConnected=\{githubAppConnected\}/);
  assert.equal(existsSync("src/features/planning/molecules/github-app-reconnect-banner.tsx"), false);
  assert.match(githubStatus, /GitHub-App-Verbindung/);
  assert.match(githubStatus, /state\?: GitHubAppConnectionState/);
  assert.match(githubStatus, /effectiveState === "checking" \|\| effectiveState === "unknown"/);
  assert.match(githubStatus, /needsAction &&/);
  assert.match(githubStatus, /GitHub-App verbinden/);
  assert.match(githubStatus, /GitHub-Sync, Kommentare und Anhänge/);
  assert.doesNotMatch(notificationsOverviewUi, /GitHub-Verbindung .*erneuern/);
  assert.doesNotMatch(notificationsOverviewUi, /zentrale Verbindung im Header/);
  assert.doesNotMatch(detailGitHubSyncCard, /GitHub-Verbindung .*erneuern/);
  assert.doesNotMatch(detailGitHubSyncCard, /frische Autorisierung/);
  assert.match(commentBody, /GitHubCommentImage/);
  assert.match(thread, /TaskCommentComposer/);
  assert.match(taskDetailWorkflow, /useTaskComments/);
  assert.match(commentHook, /createTaskCommentRequest/);
  assert.match(commentHook, /const addComment = async/);
  assert.doesNotMatch(commentHook.match(/const addComment = async[\s\S]*?const uploadAttachment/)?.[0] || "", /setGithubCommentImportPending/);
  assert.match(collaborationHook, /const addTaskComment = async/);
  assert.doesNotMatch(collaborationHook.match(/const addTaskComment = async[\s\S]*?const uploadTaskAttachment/)?.[0] || "", /setCommentImportPendingTaskIds|startTransition/);
  assert.doesNotMatch(commentHook, /x-github-provider-token|getRememberedGitHubProviderToken|getBrowserSupabase|auth\.getSession/);
  assert.match(commentComposer, /onUploadAttachment/);
  assert.match(commentComposer, /await onAddComment\(comment\)/);
  assert.match(commentComposer, /current === comment \? "" : current/);
  assert.match(commentComposer, /submitPending/);
  assert.match(githubCommentImage, /loadGitHubAssetBlob/);
  assert.doesNotMatch(githubCommentImage, /getBrowserSupabase|getRememberedGitHubProviderToken|auth\.getSession/);
  assert.doesNotMatch(taskApiClient, /includeGitHubToken|x-github-provider-token/);
  assert.equal(existsSync("src/lib/github-provider-token.ts"), false);
  assert.equal(existsSync("src/lib/github-provider-auth.ts"), false);
  assert.doesNotMatch(notificationsOverviewUi, /onReconnectGitHub/);
  assert.doesNotMatch(detailGitHubSyncCard, /onReconnectGitHub/);
  assert.doesNotMatch(notificationsOverviewUi, /GitHub-App/);
  assert.match(syncRoute, /getGitHubAppInstallationToken/);
  assert.doesNotMatch(syncRoute, /requireMatchingGitHubProviderToken|x-github-provider-token|provider_token/);
  assert.match(connectRoute, /getServerPlanningAuth\(\["ceo", "founder", "deputy", "viewer"\]\)/);
  assert.match(connectRoute, /createGitHubAppOAuthState/);
  assert.match(connectRoute, /githubAppAuthorizationUrl/);
  assert.match(appCallbackRoute, /verifyGitHubAppOAuthState/);
  assert.match(appCallbackRoute, /exchangeGitHubAppCode/);
  assert.match(appCallbackRoute, /githubUserForAppUserToken/);
  assert.match(appCallbackRoute, /storeGitHubAppUserToken/);
  assert.match(appStatusRoute, /requireTeamMember/);
  assert.match(appStatusRoute, /getGitHubAppConnectionStatus/);
  assert.match(appConnectionRoute, /export async function DELETE/);
  assert.match(appConnectionRoute, /revokeGitHubAppUserConnection/);
  assert.match(githubApp, /GITHUB_APP_ID/);
  assert.match(githubApp, /GITHUB_APP_CLIENT_ID/);
  assert.match(githubApp, /GITHUB_APP_CLIENT_SECRET/);
  assert.match(githubApp, /GITHUB_APP_INSTALLATION_ID/);
  assert.match(githubApp, /GITHUB_TOKEN_ENCRYPTION_KEY/);
  assert.match(githubApp, /aes-256-gcm/);
  assert.match(githubApp, /encrypted_access_token/);
  assert.match(githubApp, /encrypted_refresh_token/);
  assert.match(githubApp, /refreshGitHubAppUserToken/);
  assert.match(githubApp, /delete\(\)\.eq\("profile_id"/);
  assert.match(githubAppMigration, /create table if not exists github_app_user_tokens/);
  assert.match(githubAppMigration, /encrypted_access_token/);
  assert.match(githubAppMigration, /encrypted_refresh_token/);
  assert.match(githubAppMigration, /enable row level security/);
  assert.match(githubAppMigration, /grant select, insert, update, delete on github_app_user_tokens to service_role/);
  assert.doesNotMatch(githubAppMigration, /create policy/i);
  assert.match(commentsRoute, /createGitHubIssueComment/);
  assert.match(commentsRoute, /getGitHubAppUserToken/);
  assert.doesNotMatch(commentsRoute, /GitHubAppUserTokenRequiredError/);
  assert.ok(commentsRoute.indexOf('.from("task_comments")') < commentsRoute.indexOf("await getGitHubAppUserToken"));
  assert.match(commentsRoute, /githubSyncError/);
  assert.match(attachmentRoute, /getGitHubAppUserToken/);
  assert.match(attachmentRoute, /GitHubAppUserTokenRequiredError/);
  assert.match(attachmentRoute, /401/);
  assert.doesNotMatch(attachmentRoute, /requireMatchingGitHubProviderToken|x-github-provider-token|provider_token/);
  assert.doesNotMatch(commentsRoute, /task_comments"\)\.delete/);
  assert.match(github, /createGitHubIssueComment/);
  assert.match(github, /uploadGitHubAttachment/);
  assert.match(github, /getGitHubIssue/);
  assert.match(github, /api\.github\.com\/repos\/\$\{owner\}\/\$\{repo\}\/contents/);
  assert.match(rules, /GitHub App installation tokens/);
  assert.match(rules, /GitHub App user tokens/);
  assert.match(rules, /Never expose raw GitHub tokens/);
  assert.match(authDocs, /```mermaid/);
  assert.match(authDocs, /Production Boot/);
  assert.match(authDocs, /GitHub App Connect/);
  assert.match(authDocs, /GitHub API Credential Rules/);
  assert.match(authDocs, /must not start OAuth only because a task was opened/);
  assert.match(authDocs, /GitHub App user tokens are never exposed/);
  assert.doesNotMatch(syncRoute, /GITHUB_SYNC_TOKEN/);
  assert.doesNotMatch(commentsRoute, /GITHUB_SYNC_TOKEN/);
  assert.doesNotMatch(`${browserApiClient}\n${authHook}\n${syncRoute}\n${commentsRoute}\n${attachmentRoute}`, /x-github-provider-token|provider_token|logged_in_github_user_provider_token/);
});

test("comments blockers and notification outbox are modeled before Google Chat delivery", async () => {
  const migration = await readFile("supabase/0005_comments_blockers_notifications.sql", "utf8");
  const externalMigration = await readFile("supabase/0018_task_external_comments.sql", "utf8");
  const data = await readFile("src/lib/planning-data-loader.ts", "utf8");
  const commentsRoute = await readFile("src/app/api/tasks/[id]/comments/route.ts", "utf8");
  const githubCommentsRoute = await readFile("src/app/api/tasks/[id]/github-comments/route.ts", "utf8");
  const githubAssetsRoute = await readFile("src/app/api/github-assets/route.ts", "utf8");
  const attachmentRoute = await readFile("src/app/api/tasks/[id]/attachments/route.ts", "utf8");
  const blockersRoute = await readFile("src/app/api/tasks/[id]/blockers/route.ts", "utf8");
  const taskRoute = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const taskMutationContract = await readFile("src/features/tasks/model/task-mutation-contract.ts", "utf8");
  const syncRoute = await readFile("src/app/api/tasks/[id]/sync-github/route.ts", "utf8");
  const ui = await readPlanningSurface();
  const sprintUi = await readFeatureSurface("src/features/sprint");
  const panel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  const panelBlockerSection = await readFile("src/features/tasks/molecules/task-detail-panel-blocker-section.tsx", "utf8");
  const thread = await readFile("src/features/tasks/organisms/task-comment-thread.tsx", "utf8");
  const commentHook = await readFile("src/features/tasks/hooks/use-task-comments.ts", "utf8");
  const taskApiClient = await readFile("src/features/tasks/model/task-api-client.ts", "utf8");
  const commentBody = await readFile("src/features/tasks/atoms/task-comment-body.tsx", "utf8");
  const commentComposer = await readFile("src/features/tasks/molecules/task-comment-composer.tsx", "utf8");
  const commentTimeline = await readFile("src/features/tasks/molecules/task-comment-timeline.tsx", "utf8");
  const githubCommentImage = await readFile("src/features/tasks/molecules/github-comment-image.tsx", "utf8");
  const mentions = await readFile("src/lib/mentions.ts", "utf8");
  const notificationPolicy = await readFile("src/lib/notification-catalog.ts", "utf8");
  const googleChat = await readFile("src/lib/google-chat.ts", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");

  assert.match(migration, /create table if not exists task_comments/);
  assert.match(externalMigration, /create table if not exists task_external_comments/);
  assert.match(externalMigration, /unique \(source, external_id\)/);
  assert.match(migration, /create table if not exists task_blockers/);
  assert.match(migration, /create table if not exists notification_events/);
  assert.match(migration, /review_due_at/);
  assert.match(data, /taskComments/);
  assert.match(data, /taskExternalComments/);
  assert.match(data, /task_external_comments/);
  assert.match(data, /taskBlockers/);
  assert.match(data, /taskActivity/);
  assert.match(data, /task_activity/);
  assert.match(data, /notificationEvents/);
  assert.match(commentsRoute, /task.comment/);
  assert.match(commentsRoute, /mentionedProfileIds/);
  assert.match(commentsRoute, /task.mention/);
  assert.match(commentsRoute, /Du wurdest erwähnt/);
  assert.match(commentsRoute, /Kommentar hinzugefügt/);
  assert.match(mentions, /githubLogin/);
  assert.match(notificationPolicy, /task\.mention/);
  assert.match(notificationPolicy, /Erwähnung/);
  assert.match(googleChat, /eventUrl/);
  assert.match(googleChat, /\/tasks\/\$\{encodeURIComponent\(event\.entityId\)\}/);
  assert.match(googleChat, /Aufgabe öffnen/);
  assert.match(attachmentRoute, /requireFounder/);
  assert.match(attachmentRoute, /uploadGitHubAttachment/);
  assert.match(attachmentRoute, /\.fmd-attachments\/tasks/);
  assert.match(attachmentRoute, /10 MB/);
  assert.match(attachmentRoute, /markdown/);
  assert.match(githubCommentsRoute, /listGitHubIssueComments/);
  assert.match(githubCommentsRoute, /getGitHubIssue/);
  assert.match(githubCommentsRoute, /extractEvidenceFromIssueBody/);
  assert.match(githubCommentsRoute, /Nachweis aus externer Ablage importiert/);
  assert.match(githubCommentsRoute, /evidenceLink/);
  assert.match(githubCommentsRoute, /isAppMirroredComment/);
  assert.match(githubCommentsRoute, /task_external_comments/);
  assert.match(githubCommentsRoute, /source,external_id/);
  assert.doesNotMatch(githubCommentsRoute, /events/);
  assert.match(blockersRoute, /task.blocker_reported/);
  assert.match(taskMutationContract, /Status geändert/);
  assert.match(taskRoute, /activityMessages/);
  assert.match(syncRoute, /GitHub-Sync ausgeführt/);
  assert.match(panel, /TaskDetailPanelBlockerSection/);
  assert.match(panelBlockerSection, /Blocker melden/);
  assert.match(panel, /TaskCommentThread/);
  assert.match(ui, /selectedTaskActivity/);
  assert.match(commentHook, /useTaskComments/);
  assert.match(taskApiClient, /api\/tasks\/\$\{taskId\}\/comments/);
  assert.match(taskApiClient, /api\/tasks\/\$\{taskId\}\/attachments/);
  assert.match(taskApiClient, /api\/tasks\/\$\{taskId\}\/github-comments/);
  assert.match(commentComposer, /mentionOptions/);
  assert.match(commentComposer, /insertMention/);
  assert.match(commentHook, /Kommentar konnte nicht gespeichert werden/);
  assert.match(commentHook, /Anhang konnte nicht hochgeladen werden/);
  assert.match(commentHook, /GitHub-Kommentare konnten nicht aktualisiert werden/);
  assert.match(commentHook, /autoImportedGitHubCommentsRef/);
  assert.match(thread, /Kommunikation/);
  assert.match(thread, /activities/);
  assert.match(thread, /externalComments/);
  assert.match(thread, /GitHub aktualisieren/);
  assert.match(thread, /github-comment/);
  assert.match(thread, /timeline/);
  assert.match(thread, /TaskCommentTimeline/);
  assert.match(commentTimeline, /describeActivity/);
  assert.match(commentTimeline, /repairGermanText/);
  assert.match(commentTimeline, /activityToneClass/);
  assert.match(commentTimeline, /Status geändert/);
  assert.match(commentTimeline, /Review finalisiert/);
  assert.match(commentTimeline, /Abhängigkeit/);
  assert.match(thread, /CommentBody/);
  assert.match(thread, /TaskCommentComposer/);
  assert.match(githubCommentImage, /<img\b/);
  assert.match(commentBody, /react-markdown/);
  assert.match(commentBody, /remark-gfm/);
  assert.match(commentBody, /remark-breaks/);
  assert.match(commentBody, /GitHubCommentImage/);
  assert.match(commentBody, /overflow-x-auto/);
  assert.match(commentBody, /\[overflow-wrap:anywhere\]/);
  assert.match(commentBody, /skipHtml/);
  assert.match(githubCommentImage, /loadGitHubAssetBlob/);
  assert.match(taskApiClient, /\/api\/github-assets\?url=/);
  assert.match(githubCommentImage, /URL\.createObjectURL/);
  assert.match(commentBody, /safeHref/);
  assert.match(githubCommentImage, /useState\(false\)/);
  assert.match(githubCommentImage, /loadViaProxy/);
  assert.match(githubCommentImage, /if \(!isGitHubAsset \|\| proxyAttempted\)/);
  assert.match(commentComposer, /showCommentPreview/);
  assert.match(commentComposer, /Vorschau/);
  assert.match(commentComposer, /renderPreview/);
  assert.match(githubCommentImage, /loadGitHubAssetBlob/);
  assert.match(commentComposer, /onUploadAttachment/);
  assert.match(commentComposer, /type="file"/);
  assert.match(commentComposer, /Paperclip/);
  assert.match(commentComposer, /Anhang/);
  assert.match(githubAssetsRoute, /requireFounder/);
  assert.match(githubAssetsRoute, /getGitHubAppInstallationToken/);
  assert.match(githubCommentsRoute, /getGitHubAppInstallationToken/);
  assert.match(attachmentRoute, /getGitHubAppUserToken/);
  assert.doesNotMatch(githubAssetsRoute, /requireMatchingGitHubProviderToken|x-github-provider-token|provider_token/);
  assert.match(githubAssetsRoute, /user-attachments\/assets/);
  assert.match(githubAssetsRoute, /content-type/);
  assert.match(githubAssetsRoute, /image\//);
  assert.match(githubCommentImage, /Anhang in GitHub öffnen/);
  assert.match(thread, /new Date\(left\.createdAt\)/);
  assert.match(commentTimeline, /Nachfragen/);
  assert.match(commentComposer, /Kommentieren/);
  assert.match(types, /TaskActivity/);
  assert.match(types, /TaskExternalComment/);
  assert.match(sprintUi, /Review bis/);
});
