import { readFile } from "node:fs/promises";
import { readPlanningSurface } from "./helpers/planning-surface.mjs";
import test from "node:test";
import assert from "node:assert/strict";

test("working status stays ownership-bound while Sub-Issue final transitions are role-based", async () => {
  const route = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const routeHelpers = await readFile("src/features/tasks/model/task-route-update-helpers.ts", "utf8");
  const routePolicy = `${route}\n${routeHelpers}`;
  const app = await readPlanningSurface();
  const taskCard = await readFile("src/features/tasks/molecules/task-card.tsx", "utf8");
  const detailPanel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  const detailSurface = await readFile("src/features/tasks/organisms/task-detail-surface.tsx", "utf8");
  const detailPermissions = await readFile("src/features/tasks/model/task-detail-permissions.ts", "utf8");
  const operationalHeader = await readFile("src/features/tasks/molecules/task-detail-operational-header.tsx", "utf8");
  const statusControl = await readFile("src/features/tasks/atoms/task-status-control.tsx", "utf8");

  assert.match(routePolicy, /taskAssignedToProfile/);
  assert.match(routePolicy, /Founder können nur den Status ihrer eigenen Aufgaben ändern/);
  assert.match(routePolicy, /roleBasedFinalTransition/);
  assert.match(routePolicy, /validateSubIssueStatusParentApproval/);
  assert.match(app, /canChangeTaskStatus/);
  assert.match(app, /canManageFinalTaskStatus/);
  assert.match(app, /taskBelongsToProfile\(task, currentProfile\)/);
  assert.match(app, /onDragStart=\{canUpdateStatus && onDragStart \? onDragStart : undefined\}/);
  assert.match(taskCard, /statusDisabled/);
  assert.match(detailPanel, /TaskDetailSurface/);
  assert.match(detailSurface, /permissions\.canUpdateStatus/);
  assert.match(detailSurface, /permissions\.canCompleteSubIssue/);
  assert.match(detailSurface, /permissions\.canReopenSubIssue/);
  assert.match(detailPermissions, /taskOwnedByProfile/);
  assert.match(detailPermissions, /canContributorManageSubIssueFinalStatus/);
  assert.match(operationalHeader, /TaskStatusControl/);
  assert.match(detailSurface, /taskStatusOptionsForPermissions/);
  assert.match(statusControl, /lockedReason/);
  assert.match(statusControl, /isTaskStatusChange/);
});

test("header overlays close on outside click and escape", async () => {
  const notifications = await readFile("src/features/notifications/organisms/notification-inbox.tsx", "utf8");
  const calendar = await readFile("src/features/events/molecules/header-event-calendar.tsx", "utf8");

  assert.match(notifications, /rootRef/);
  assert.match(notifications, /pointerdown/);
  assert.match(notifications, /keydown/);
  assert.match(notifications, /href="\/notifications"/);
  assert.match(calendar, /rootRef/);
  assert.match(calendar, /pointerdown/);
  assert.match(calendar, /Escape/);
});

test("repo readiness includes the GitHub Actions deployment pipeline gates", async () => {
  const verify = await readFile("scripts/verify-vercel-ready.mjs", "utf8");
  const vercelJson = await readFile("vercel.json", "utf8");
  const previewWorkflow = await readFile(".github/workflows/deploy-preview.yml", "utf8");
  const productionWorkflow = await readFile(".github/workflows/deploy-production.yml", "utf8");
  const deployScript = await readFile(".github/scripts/deploy/vercel-deploy-prebuilt.sh", "utf8");
  const migrationDeployScript = await readFile("scripts/deploy-production-migrations.mjs", "utf8");
  const migrationContract = await readFile("scripts/lib/supabase-migrations.mjs", "utf8");
  const migrationVerifier = await readFile("scripts/verify-supabase-migrations.mjs", "utf8");
  const schemaConnection = await readFile("scripts/lib/production-schema-connection.mjs", "utf8");
  const dependabot = await readFile(".github/dependabot.yml", "utf8");
  const gitignore = await readFile(".gitignore", "utf8");
  const deployment = await readFile("docs/vercel-deployment.md", "utf8");
  const pkg = await readFile("package.json", "utf8");
  const layout = await readFile("src/app/layout.tsx", "utf8");
  const css = await readFile("src/app/globals.css", "utf8");
  const ui = await readPlanningSurface();

  assert.match(verify, /ready-for-github-actions-deployment/);
  assert.match(verify, /deploy-preview\.yml/);
  assert.match(verify, /deploy-production\.yml/);
  assert.match(verify, /vercel\.json/);
  assert.match(verify, /githubEnvironments/);
  assert.match(verify, /founder-ops\.findmydoc\.eu/);
  assert.match(verify, /\.github\/dependabot\.yml/);
  assert.match(verify, /GOOGLE_CHAT_DELIVERY_ENABLED/);
  assert.match(verify, /verify:google-chat/);
  assert.match(verify, /GITHUB_SYNC_TOKEN/);
  assert.doesNotMatch(verify, /manualNextSteps/);
  assert.match(vercelJson, /"installCommand": "pnpm install --frozen-lockfile"/);
  assert.match(vercelJson, /"buildCommand": "pnpm run vercel:build"/);
  assert.match(previewWorkflow, /environment:[\s\S]*name: preview/);
  assert.match(previewWorkflow, /url: \$\{\{ steps\.vercel_preview\.outputs\.deploymentUrl \}\}/);
  assert.match(previewWorkflow, /github\.event_name == 'push'/);
  assert.match(previewWorkflow, /github\.event\.pull_request\.head\.repo\.full_name == github\.repository/);
  assert.match(previewWorkflow, /Validate preview secrets/);
  assert.match(previewWorkflow, /preview_guard/);
  assert.match(previewWorkflow, /pull --yes --environment=preview/);
  assert.match(previewWorkflow, /EXPECTED_VERCEL_PROJECT_ID/);
  assert.match(previewWorkflow, /assert-vercel-project-binding\.sh/);
  assert.match(previewWorkflow, /Build Vercel Output/);
  assert.match(previewWorkflow, /build --target=preview/);
  assert.match(previewWorkflow, /vercel-deploy-prebuilt\.sh preview/);
  assert.match(productionWorkflow, /environment:[\s\S]*name: production/);
  assert.match(productionWorkflow, /url: \$\{\{ steps\.vercel_production\.outputs\.deploymentUrl \}\}/);
  assert.match(productionWorkflow, /refs\/heads\/main/);
  assert.match(productionWorkflow, /pull --yes --environment=production/);
  assert.match(productionWorkflow, /EXPECTED_VERCEL_PROJECT_ID/);
  assert.match(productionWorkflow, /assert-vercel-project-binding\.sh/);
  assert.match(productionWorkflow, /Build Vercel Output[\s\S]*NEXT_PUBLIC_SUPABASE_URL: \$\{\{ secrets\.NEXT_PUBLIC_SUPABASE_URL \}\}/);
  assert.match(productionWorkflow, /Build Vercel Output[\s\S]*NEXT_PUBLIC_SUPABASE_ANON_KEY: \$\{\{ secrets\.NEXT_PUBLIC_SUPABASE_ANON_KEY \}\}/);
  assert.match(productionWorkflow, /build --prod/);
  assert.match(productionWorkflow, /Verify Supabase Migration History/);
  assert.match(productionWorkflow, /Apply Supabase Migrations to Production/);
  assert.match(productionWorkflow, /SCHEMA_DEPLOY_TARGET: production/);
  assert.match(productionWorkflow, /SUPABASE_DB_HOST: \$\{\{ secrets\.SUPABASE_DB_HOST \}\}/);
  assert.match(productionWorkflow, /SUPABASE_DB_USER: \$\{\{ secrets\.SUPABASE_DB_USER \}\}/);
  assert.match(productionWorkflow, /SUPABASE_DB_PASSWORD: \$\{\{ secrets\.SUPABASE_DB_PASSWORD \}\}/);
  assert.match(productionWorkflow, /pnpm run verify:migrations/);
  assert.match(productionWorkflow, /pnpm run deploy:supabase-migrations/);
  assert.match(productionWorkflow, /Verify Production Supabase Schema/);
  assert.match(productionWorkflow, /pnpm run verify:supabase/);
  assert.match(productionWorkflow, /pnpm run deploy:supabase-migrations[\s\S]*pnpm run verify:supabase[\s\S]*vercel-deploy-prebuilt\.sh production/);
  assert.doesNotMatch(productionWorkflow, /deploy:github-sync-migrations|rollback:github-sync-fields/);
  assert.match(productionWorkflow, /vercel-deploy-prebuilt\.sh production/);
  assert.match(productionWorkflow, /NEXT_PUBLIC_SUPABASE_URL/);
  assert.match(productionWorkflow, /SUPABASE_SERVICE_ROLE_KEY/);
  assert.match(productionWorkflow, /APP_URL/);
  assert.match(productionWorkflow, /GITHUB_SYNC_OWNER: findmydoc-platform/);
  assert.match(deployScript, /RUNNER_TEMP/);
  assert.match(deployScript, /git archive HEAD/);
  assert.match(deployScript, /\.vercel\/output/);
  assert.match(deployScript, /\.vercel\/project\.json/);
  assert.match(deployScript, /node_modules is missing/);
  assert.match(deployScript, /pnpm-lock\.yaml/);
  assert.match(deployScript, /node_modules/);
  assert.match(deployScript, /\.next\/package\.json is missing/);
  assert.match(deployScript, /\.next/);
  assert.match(deployScript, /Refusing to deploy: staging directory contains Git metadata\./);
  assert.match(deployScript, /--prebuilt/);
  assert.match(deployScript, /--no-wait/);
  assert.match(deployScript, /--target=preview/);
  assert.match(deployScript, /--prod/);
  assert.match(deployScript, /assert-vercel-project-binding\.sh/);
  assert.match(deployScript, /promote/);
  assert.match(deployScript, /already the current production deployment/);
  assert.match(deployScript, /already-current/);
  assert.match(deployScript, /if \[\[ "\$\{target\}" == "production" \]\][\s\S]*promote_command=/);
  assert.match(deployScript, /--timeout=3m/);
  assert.match(deployScript, /Production promotion failed/);
  assert.match(deployScript, /inspect/);
  assert.match(deployScript, /readyStateReason/);
  assert.match(deployScript, /seatBlock/);
  assert.match(deployScript, /TEAM_ACCESS_REQUIRED/);
  assert.match(deployScript, /deploymentUrl=/);
  assert.match(migrationDeployScript, /SCHEMA_DEPLOY_TARGET/);
  assert.match(migrationDeployScript, /refs\/heads\/main/);
  assert.match(migrationDeployScript, /resolveProductionSchemaConnection/);
  assert.match(schemaConnection, /SUPABASE_DB_HOST/);
  assert.match(schemaConnection, /SUPABASE_DB_USER/);
  assert.match(schemaConnection, /SUPABASE_DB_PASSWORD/);
  assert.match(schemaConnection, /pooler\.supabase\.com/);
  assert.match(migrationDeployScript, /supabase_migrations\.schema_migrations/);
  assert.match(migrationDeployScript, /productionBaseline/);
  assert.match(migrationDeployScript, /github_issue_sync_locks/);
  assert.match(migrationDeployScript, /"db", "push"/);
  assert.match(migrationDeployScript, /"--dry-run"/);
  assert.match(migrationDeployScript, /notify pgrst, 'reload schema'/);
  assert.match(migrationContract, /drop\\s\+table/);
  assert.match(migrationVerifier, /2\.109\.1/);
  assert.match(migrationVerifier, /no longer matches the verified production dump/);
  assert.doesNotMatch(previewWorkflow, /VERCEL_TOKEN is required/);
  assert.doesNotMatch(previewWorkflow, /SUPABASE_DB_HOST/);
  assert.doesNotMatch(previewWorkflow, /SUPABASE_DB_USER/);
  assert.doesNotMatch(previewWorkflow, /SUPABASE_DB_PASSWORD/);
  assert.doesNotMatch(productionWorkflow, /VERCEL_TOKEN is required/);
  assert.match(pkg, /verify:release/);
  assert.match(pkg, /verify:deploy/);
  assert.match(pkg, /vercel:build/);
  assert.match(pkg, /verify:migrations/);
  assert.match(pkg, /deploy:supabase-migrations/);
  assert.match(pkg, /db:migration:new/);
  assert.match(pkg, /db:reset/);
  assert.match(pkg, /"supabase": "2\.109\.1"/);
  assert.doesNotMatch(pkg, /deploy:supabase-schema|deploy:github-sync-migrations|rollback:github-sync-fields|apply:sql/);
  assert.match(pkg, /pnpm run verify:migrations && pnpm test/);
  assert.match(pkg, /node --test tests\/\*\.test\.mjs/);
  assert.match(pkg, /eslint/);
  assert.match(pkg, /node scripts\/verify-vercel-ready\.mjs/);
  assert.match(pkg, /node scripts\/verify-google-chat-rollout\.mjs/);
  assert.match(pkg, /pnpm audit --audit-level=moderate/);
  assert.doesNotMatch(pkg, /"verify:release": ".*next build/);
  assert.match(gitignore, /\.github\/workflows\/ci\.yml/);
  assert.match(dependabot, /package-ecosystem: npm/);
  assert.match(dependabot, /package-ecosystem: github-actions/);
  assert.match(dependabot, /timezone: Europe\/Berlin/);
  assert.match(dependabot, /nextjs-stack/);
  assert.match(deployment, /GitHub Actions/);
  assert.match(deployment, /GitHub Actions Deployment Workflow/);
  assert.match(deployment, /GitHub Environments/);
  assert.match(deployment, /VERCEL_TOKEN/);
  assert.match(deployment, /VERCEL_ORG_ID/);
  assert.match(deployment, /VERCEL_PROJECT_ID/);
  assert.match(deployment, /SUPABASE_DB_PASSWORD/);
  assert.match(deployment, /SUPABASE_DB_HOST/);
  assert.match(deployment, /SUPABASE_DB_USER/);
  assert.match(deployment, /pnpm run deploy:supabase-migrations/);
  assert.match(deployment, /SCHEMA_DEPLOY_TARGET=production/);
  assert.match(deployment, /supabase\/migrations\/20260713120959_production_baseline\.sql/);
  assert.match(deployment, /migration repair/);
  assert.match(deployment, /14 days/);
  assert.match(deployment, /forward-only/);
  assert.match(deployment, /founder-ops\.findmydoc\.eu/);
  assert.match(deployment, /pnpm run vercel:build/);
  assert.match(deployment, /GOOGLE_CHAT_DELIVERY_ENABLED=false/);
  assert.match(deployment, /Operational event messages stay inside the application/);
  assert.match(deployment, /preview secrets are missing/);
  assert.match(deployment, /Do not configure a shared `GITHUB_SYNC_TOKEN`/);
  assert.match(deployment, /pnpm run verify:deploy/);
  assert.match(deployment, /GitHub Actions job logs/);
  assert.match(deployment, /Git-metadata-free runner directory/);
  assert.match(deployment, /Vercel Hobby Private Repository Author Block/);
  assert.match(deployment, /readyStateReason/);
  assert.match(deployment, /seatBlock/);
  assert.doesNotMatch(deployment, /vercel link --yes --project founder-ops/);
  assert.doesNotMatch(deployment, /vercel login/);
  assert.doesNotMatch(deployment, /vercel deploy/);
  assert.doesNotMatch(deployment, /vercel build --prod/);
  assert.doesNotMatch(deployment, /vercel inspect/);
  assert.doesNotMatch(deployment, /vercel logs/);
  assert.doesNotMatch(layout, /next\/font\/google/);
  assert.match(css, /--font-sans: Inter, ui-sans-serif/);
  assert.match(ui, /NotificationsOverview/);
  assert.doesNotMatch(ui, /Betriebsdetails|manuell offen|Deployment-Automation/);
  assert.doesNotMatch(ui, /vercel login/);
  assert.doesNotMatch(ui, /Release-Prüfung|GitHub-Zugriff|Anmelde-Weiterleitungen/);
});
