import { readFile } from "node:fs/promises";
import { readFeatureSurface, readPlanningSurface } from "./helpers/planning-surface.mjs";
import test from "node:test";
import assert from "node:assert/strict";

test("fmd tools workspace keeps internal tools repos notion and drive visible", async () => {
  const migration = await readFile("supabase/0015_fmd_tools_hub.sql", "utf8");
  const ui = await readPlanningSurface();
  const toolsUi = await readFile("src/features/tools/organisms/fmd-quick-links-overview.tsx", "utf8");
  const toolDialog = await readFile("src/features/tools/molecules/fmd-quick-link-dialog.tsx", "utf8");
  const toolRow = await readFile("src/features/tools/molecules/fmd-quick-link-card.tsx", "utf8");
  const toolsModel = await readFile("src/features/tools/model/fmd-tools.ts", "utf8");
  const quickLinks = await readFile("src/features/tools/molecules/fmd-tool-quick-links.tsx", "utf8");
  const toolsSurface = await readFeatureSurface("src/features/tools");
  const toolRoute = await readFile("src/app/api/tools/route.ts", "utf8");
  const toolUpdateRoute = await readFile("src/app/api/tools/[id]/route.ts", "utf8");
  const toolCommands = await readFile("src/features/tools/hooks/use-fmd-tool-commands.ts", "utf8");
  const toolRegistrationMigration = await readFile("supabase/0039_fmd_tools_team_registration.sql", "utf8");
  const toolSeedExamplesMigration = await readFile("supabase/0040_quicklinks_seed_examples.sql", "utf8");
  const toolCuratedLinksMigration = await readFile("supabase/0041_fmd_tools_curated_links.sql", "utf8");
  const toolPreviewMigration = await readFile("supabase/0042_fmd_tools_preview_images.sql", "utf8");
  const toolLegacyBackfillMigration = await readFile("supabase/0043_backfill_legacy_quicklink_links.sql", "utf8");
  const toolMetadataRoute = await readFile("src/app/api/tools/metadata/route.ts", "utf8");
  const toolPreviewRoute = await readFile("src/app/api/tools/preview-image/route.ts", "utf8");
  const toolMetadataHelper = await readFile("src/lib/fmd-tool-metadata.ts", "utf8");
  const planningApiClient = await readFile("src/features/planning/model/planning-api-client.ts", "utf8");
  const planningAppModel = await readFile("src/features/planning/model/planning-app-model.ts", "utf8");
  const header = await readFile("src/features/planning/organisms/planning-header.tsx", "utf8");
  const headerActions = await readFile("src/features/planning/molecules/planning-header-data-actions.tsx", "utf8");
  const headerData = await readFile("src/lib/planning-header-data.ts", "utf8");
  const data = await readFile("src/lib/planning-data-loader.ts", "utf8");
  const schemaChecks = await readFile("src/lib/planning-schema-checks.json", "utf8");
  const seed = await readFile("src/lib/seed/source.json", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");

  assert.match(migration, /create table if not exists fmd_tools/);
  assert.match(migration, /email-signature-tool/);
  assert.match(migration, /https:\/\/mailsig\.findmydoc\.eu\//);
  assert.match(migration, /'email-signature-tool'.*'active'/s);
  assert.match(migration, /investor-calculator/);
  assert.match(migration, /notion-docs-source/);
  assert.match(migration, /https:\/\/www\.notion\.so\/Team-Workspace-31c283c73e6180cf9eedc8e0694cf2db/);
  assert.match(migration, /google-drive-assets/);
  assert.match(migration, /https:\/\/drive\.google\.com\/drive\/shared-drives/);
  const pitchdeckMigration = await readFile("supabase/0021_pitchdeck_tool.sql", "utf8");
  assert.match(pitchdeckMigration, /pitchdeck-site/);
  assert.match(pitchdeckMigration, /https:\/\/pitchdeck\.findmydoc\.eu\//);
  assert.match(ui, /FmdQuickLinksOverview/);
  assert.match(toolsSurface, /Link eintragen/);
  assert.match(toolsSurface, /role="dialog"/);
  assert.match(toolsSurface, /Link bearbeiten/);
  assert.doesNotMatch(toolDialog, /Metadaten laden/);
  assert.match(toolDialog, /metadataLoadDelayMs = 900/);
  assert.match(toolDialog, /onBlur=\{triggerMetadataLoad\}/);
  assert.match(toolDialog, /CheckCircle2/);
  assert.match(toolDialog, /XCircle/);
  assert.match(toolsSurface, /Bearbeiten/);
  assert.match(toolsSurface, /CustomSelect/);
  assert.doesNotMatch(toolsSurface, /Status filtern/);
  assert.match(toolsSurface, /Filter zurücksetzen/);
  assert.match(toolsSurface, /Werkzeuge/);
  assert.match(toolsUi, /sm:grid-cols-2 xl:grid-cols-3/);
  assert.match(toolsUi, /const \[showMissingLinks, setShowMissingLinks\] = useState\(true\)/);
  assert.match(toolsUi, /visibleByLinkTools/);
  assert.match(toolsUi, /role="switch"/);
  assert.match(toolsUi, /Fehlende Links/);
  assert.match(toolsUi, /setShowMissingLinks\(true\)/);
  assert.match(toolsModel, /hasFmdToolLink/);
  assert.match(toolsModel, /Number\(hasFmdToolLink\(b\)\) - Number\(hasFmdToolLink\(a\)\)/);
  assert.match(toolsModel, /a\.name\.localeCompare\(b\.name, "de"\)/);
  assert.doesNotMatch(toolsUi, /fmdToolsTableGrid|hidden gap-4 border-b|divide-y/);
  assert.match(toolRow, /Link fehlt/);
  assert.match(toolRow, /FmdQuickLinkPreviewImage/);
  assert.match(toolRow, /previewImageUrl/);
  assert.match(toolRow, /referrerPolicy="no-referrer"/);
  assert.match(toolRow, /grid-cols-\[88px_minmax\(0,1fr\)\]/);
  assert.match(toolRow, /min-h-36/);
  assert.match(toolRow, /rounded-md border transition/);
  assert.match(toolRow, /aria-label=\{`\$\{tool\.name\} extern öffnen`\}/);
  assert.match(toolRow, /ExternalLink size=\{14\}/);
  assert.match(toolRow, /aria-label=\{`\$\{tool\.name\} bearbeiten`\}/);
  assert.match(toolRow, /title="Link bearbeiten"/);
  assert.doesNotMatch(toolRow, />\s*Öffnen\s*</);
  assert.doesNotMatch(toolRow, />\s*Bearbeiten\s*<\/UiButton>/);
  assert.match(quickLinks, /HeaderQuickLink/);
  assert.match(quickLinks, /maxHeaderQuickLinks/);
  assert.doesNotMatch(quickLinks, /curatedFmdToolLinks\(tools\)/);
  assert.match(quickLinks, /previewImageUrl/);
  assert.match(quickLinks, /aria-haspopup="dialog"/);
  assert.match(quickLinks, /Kuratierte Links/);
  assert.match(quickLinks, /closeOnOutside/);
  assert.match(quickLinks, /event\.key === "Escape"/);
  assert.match(headerActions, /FmdToolQuickLinks/);
  assert.match(headerActions, /quickLinks=\{headerData\.quickLinks\}/);
  assert.match(header, /PlanningHeaderDataActions/);
  assert.doesNotMatch(header, /tools=\{data\.fmdTools\}/);
  assert.doesNotMatch(header, /workspace === "tools"/);
  assert.match(headerData, /headerQuickLinkSelect = "id,name,category,url,preview_image_url"/);
  assert.match(headerData, /\.eq\("is_curated", true\)/);
  assert.match(headerData, /\.limit\(maxHeaderQuickLinks\)/);
  assert.doesNotMatch(toolsUi, /MetricBlock/);
  assert.doesNotMatch(toolsUi, /<div>Status<\/div>|<div>Link<\/div>|<div>Art<\/div>|<div>Aktion<\/div>/);
  assert.doesNotMatch(toolsUi, /Werkzeugraum|Tool eintragen|Tool-Eintragung/);
  assert.doesNotMatch(toolsUi, /Interne Tools, Repos, Wissen und Assets/);
  assert.doesNotMatch(planningAppModel, /tools: "Interne Tools, Repos, Wissen und Assets/);
  assert.doesNotMatch(toolsSurface, /bg-red-600|bg-yellow-300|border-t-red-600/);
  assert.match(toolRoute, /requireTeamMember/);
  assert.match(toolRoute, /fmd_tool\.create/);
  assert.match(toolRoute, /slugify/);
  assert.match(toolUpdateRoute, /requireTeamMember/);
  assert.match(toolUpdateRoute, /export async function PATCH/);
  assert.match(toolUpdateRoute, /fmd_tool\.update/);
  assert.match(toolCommands, /new URL\(value\)/);
  assert.match(toolCommands, /fmdToolStatusFromUrl\(url\)/);
  assert.match(toolCommands, /maxCuratedFmdToolLinks/);
  assert.match(toolCommands, /updateFmdTool/);
  assert.match(planningApiClient, /updateFmdToolRequest/);
  assert.match(planningApiClient, /requestFmdToolMetadata/);
  assert.match(planningApiClient, /uploadFmdToolPreviewImageRequest/);
  assert.match(toolCommands, /Link muss mit http:\/\/ oder https:\/\/ beginnen\./);
  assert.match(toolCommands, /previewImageUrl/);
  assert.match(toolRegistrationMigration, /fmd_tools_insert_team/);
  assert.match(toolRegistrationMigration, /'viewer'/);
  assert.match(toolRegistrationMigration, /fmd_tools_update_team/);
  assert.match(toolSeedExamplesMigration, /offer-calculator/);
  assert.match(toolSeedExamplesMigration, /tool-repos/);
  assert.match(toolSeedExamplesMigration, /clinic-outreach-crm/);
  assert.match(toolSeedExamplesMigration, /brand-asset-library/);
  assert.match(toolCuratedLinksMigration, /add column if not exists is_curated/);
  assert.match(toolCuratedLinksMigration, /email-signature-tool/);
  assert.match(toolCuratedLinksMigration, /google-drive-assets/);
  assert.match(toolPreviewMigration, /preview_image_url/);
  assert.match(toolPreviewMigration, /preview_image_source/);
  assert.match(toolPreviewMigration, /fmd-tool-previews/);
  assert.match(toolPreviewMigration, /image\/webp/);
  assert.match(toolLegacyBackfillMigration, /email-signature-tool/);
  assert.match(toolLegacyBackfillMigration, /https:\/\/mailsig\.findmydoc\.eu\//);
  assert.match(toolLegacyBackfillMigration, /tool-repos/);
  assert.match(toolLegacyBackfillMigration, /https:\/\/github\.com\/findmydoc-platform\/management/);
  assert.match(toolLegacyBackfillMigration, /notion-docs-source/);
  assert.match(toolLegacyBackfillMigration, /https:\/\/www\.notion\.so\/Team-Workspace-31c283c73e6180cf9eedc8e0694cf2db/);
  assert.match(toolLegacyBackfillMigration, /pitchdeck-site/);
  assert.match(toolLegacyBackfillMigration, /https:\/\/pitchdeck\.findmydoc\.eu\//);
  assert.match(toolLegacyBackfillMigration, /google-drive-assets/);
  assert.match(toolLegacyBackfillMigration, /https:\/\/drive\.google\.com\/drive\/shared-drives/);
  assert.match(toolLegacyBackfillMigration, /on conflict \(id\) do nothing/);
  assert.match(toolLegacyBackfillMigration, /nullif\(btrim\(tool\.url\), ''\)/);
  assert.match(toolLegacyBackfillMigration, /where tool\.id = legacy_links\.id/);
  assert.doesNotMatch(toolLegacyBackfillMigration, /on conflict \(id\) do update/);
  assert.match(toolMetadataRoute, /requireTeamMember/);
  assert.match(toolMetadataRoute, /loadFmdToolMetadata/);
  assert.match(toolMetadataHelper, /assertPublicHttpUrl/);
  assert.match(toolMetadataHelper, /isBlockedHostname/);
  assert.match(toolMetadataHelper, /isPrivateIpAddress/);
  assert.match(toolMetadataHelper, /redirect: "manual"/);
  assert.match(toolMetadataHelper, /maxHtmlBytes = 256 \* 1024/);
  assert.doesNotMatch(toolMetadataHelper, /Authorization/);
  assert.match(toolPreviewRoute, /requireTeamMember/);
  assert.match(toolPreviewRoute, /request\.formData\(\)/);
  assert.match(toolPreviewRoute, /image\/png/);
  assert.match(toolPreviewRoute, /maxUploadBytes = 5 \* 1024 \* 1024/);
  assert.match(planningApiClient, /createFmdToolRequest/);
  assert.doesNotMatch(header, /setWorkspace\("tools"\)/);
  assert.doesNotMatch(header, /Werkzeugraum/);
  assert.match(data, /fmdTools/);
  assert.match(data, /preview_image_url,preview_image_source/);
  assert.match(schemaChecks, /preview_image_url,preview_image_source/);
  assert.match(seed, /https:\/\/mailsig\.findmydoc\.eu\//);
  assert.match(seed, /offer-calculator/);
  assert.match(seed, /tool-repos/);
  assert.match(seed, /clinic-outreach-crm/);
  assert.match(seed, /brand-asset-library/);
  assert.match(seed, /"isCurated": true/);
  assert.match(seed, /"previewImageUrl"/);
  assert.match(seed, /"previewImageSource": "og"/);
  assert.match(seed, /https:\/\/www\.notion\.so\/Team-Workspace-31c283c73e6180cf9eedc8e0694cf2db/);
  assert.match(seed, /https:\/\/pitchdeck\.findmydoc\.eu\//);
  assert.match(seed, /https:\/\/drive\.google\.com\/drive\/shared-drives/);
  assert.match(types, /export type FmdTool/);
  assert.match(types, /previewImageSource: "none" \| "og" \| "manual"/);
});

test("execution workspace is retired while focus storage remains legacy-compatible", async () => {
  const migration = await readFile("supabase/0020_execution_layer.sql", "utf8");
  const ui = await readPlanningSurface();
  const routes = await readFile("src/features/planning/model/workspace-routes.ts", "utf8");
  const executionPage = await readFile("src/app/(workspaces)/execution/page.tsx", "utf8");
  const data = await readFile("src/lib/planning-data-loader.ts", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");
  const focusRoute = await readFile("src/app/api/focus/route.ts", "utf8");
  const planningApiClient = await readFile("src/features/planning/model/planning-api-client.ts", "utf8");
  const profileSync = await readFile("src/features/profile/hooks/use-profile-ui-preference-sync.ts", "utf8");
  const profileSettingsModel = await readFile("src/features/profile/model/profile-settings-view-model.ts", "utf8");
  const profileSettingsRoute = await readFile("src/app/api/profile-settings/route.ts", "utf8");
  const taskViewModel = await readFile("src/features/planning/model/planning-task-table-view-model.ts", "utf8");
  const taskSignals = await readFile("src/features/tasks/model/task-attention-signals.ts", "utf8");
  const taskSignalBadges = await readFile("src/features/tasks/molecules/task-attention-badges.tsx", "utf8");
  const taskCard = await readFile("src/features/tasks/molecules/task-card.tsx", "utf8");
  const taskTable = await readFile("src/features/tasks/organisms/task-table-view.tsx", "utf8");
  const reviewUi = await readFile("src/features/reviews/organisms/review-workspace-overview.tsx", "utf8");
  const verify = await readFile("scripts/verify-supabase.mjs", "utf8");
  const health = await readFile("src/app/api/health/route.ts", "utf8");
  const schemaChecks = await readFile("src/lib/planning-schema-checks.json", "utf8");
  const schema = await readFile("supabase/schema.sql", "utf8");
  const detail = await readFile("src/features/tasks/templates/task-detail-page.tsx", "utf8");
  const taskPage = await readFile("src/app/tasks/[id]/page.tsx", "utf8");
  const agents = await readFile("AGENTS.md", "utf8");
  const plan = await readFile("docs/execution-layer-plan.md", "utf8");

  assert.match(migration, /create table if not exists task_focus_items/);
  assert.match(migration, /unique \(profile_id, task_id, focus_date\)/);
  assert.doesNotMatch(routes, /label: "Execution"|id: "execution"|href: "\/execution"/);
  assert.match(routes, /value === "mine" \|\| value === "execution"/);
  assert.match(executionPage, /redirect\("\/planning"\)/);
  assert.doesNotMatch(ui, /ExecutionLayerOverview|Heute-Fokus|Hygiene Alerts|Fokus-Kontext|buildHygieneAlerts/);
  assert.match(profileSync, /appWorkspaceFromValue\(value\) \|\| "planning"/);
  assert.match(profileSettingsModel, /appWorkspaceFromValue\(value\) \|\| "planning"/);
  assert.doesNotMatch(profileSettingsRoute, /"execution",/);
  assert.match(taskViewModel, /quickFilter === "critical"/);
  assert.match(taskViewModel, /taskHasCriticalAttention/);
  assert.match(taskViewModel, /taskHasMissingEvidenceAttention/);
  assert.match(taskSignals, /export type TaskAttentionSignal/);
  assert.match(taskSignals, /Owner fehlt/);
  assert.match(taskSignals, /Blocker fehlt/);
  assert.match(taskSignals, /Wartet/);
  assert.match(taskSignals, /Sync fehlgeschlagen/);
  assert.match(taskSignals, /AC fehlt/);
  assert.match(taskSignals, /DoD fehlt/);
  assert.match(taskSignals, /Evidence fehlt/);
  assert.match(taskSignals, /Review >2d/);
  assert.match(taskSignals, /Ohne Review Owner/);
  assert.doesNotMatch(taskSignals, /48 Stunden|stale|Kein Update/);
  assert.match(taskSignalBadges, /maxVisible = 2/);
  assert.match(taskCard, /TaskCardRiskBadges/);
  assert.match(taskTable, /TaskTableRiskBadges/);
  assert.match(reviewUi, /ReviewTaskAttentionBadges/);
  assert.doesNotMatch(ui, /Decision-Link entfernen|Decision-Folgearbeit|Folgeaufgabe aus Decision/);
  assert.doesNotMatch(planningApiClient, /api\/decisions\/\$\{decisionId\}\/tasks/);
  assert.match(focusRoute, /Founder können nur eigene Aufgaben in den Fokus nehmen/);
  assert.match(focusRoute, /Founder können nur eigene Fokus-Einträge entfernen/);
  assert.doesNotMatch(ui, /Abnahmekriterien fehlen|Nächste Aktion|Aktion in Fokus/);
  assert.doesNotMatch(ui, /Decision ohne Folgeaufgabe/);
  const panel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  assert.doesNotMatch(panel, /TaskDetailPanelContextSection|Fokus-Kontext/);
  assert.doesNotMatch(detail, /TaskContextSection|Fokus-Kontext|focusItems/);
  assert.doesNotMatch(detail, /decisionTaskLinks/);
  assert.doesNotMatch(taskPage, /focusItems=\{data\.taskFocusItems\}/);
  assert.doesNotMatch(taskPage, /decisionTaskLinks=\{data\.decisionTaskLinks\}/);
  assert.match(data, /taskFocusItems/);
  assert.doesNotMatch(data, /decisionTaskLinks/);
  assert.match(types, /export type TaskFocusItem/);
  assert.doesNotMatch(types, /export type DecisionTaskLink/);
  assert.match(focusRoute, /task_focus_items/);
  assert.match(focusRoute, /Heute-Fokus ist auf drei Aufgaben begrenzt/);
  assert.match(focusRoute, /export async function DELETE/);
  assert.match(focusRoute, /Fokus entfernt/);
  assert.match(focusRoute, /Fokus aktualisiert/);
  assert.match(verify, /planning-schema-checks\.json/);
  assert.doesNotMatch(health, /planning-schema-checks\.json/);
  assert.match(schemaChecks, /task_focus_items/);
  assert.doesNotMatch(schemaChecks, /decision_task_links/);
  assert.match(schema, /create table if not exists task_focus_items/);
  assert.doesNotMatch(schema, /create table if not exists decision_task_links/);
  assert.match(agents, /Execution workspace is retired/);
  assert.match(plan, /retired/);
  assert.match(plan, /TaskAttentionSignal/);
  assert.doesNotMatch(plan, /Decision-to-Task Links/);
});

test("task creation supports deliverables proposals and non scoring sub issues", async () => {
  const migration = await readFile("supabase/0006_task_creation_hierarchy.sql", "utf8");
  const route = await readFile("src/app/api/tasks/route.ts", "utf8");
  const updateRoute = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const updateRouteHelpers = await readFile("src/features/tasks/model/task-route-update-helpers.ts", "utf8");
  const updateRoutePolicy = `${updateRoute}\n${updateRouteHelpers}`;
  const promotionMigration = await readFile("supabase/0034_promote_assigned_proposals.sql", "utf8");
  const transactionalCreationMigration = await readFile("supabase/0047_transactional_task_creation_and_github_sync.sql", "utf8");
  const createCommand = await readFile("src/features/tasks/hooks/use-task-create-command.ts", "utf8");
  const ui = await readPlanningSurface();
  const newTaskUi = await readFile("src/features/tasks/organisms/new-task-dialog.tsx", "utf8");
  const display = await readFile("src/lib/display.ts", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");

  assert.match(migration, /task_type/);
  assert.match(migration, /parent_task_id/);
  assert.match(migration, /score_relevant/);
  assert.match(route, /task\.proposed/);
  assert.match(route, /create_task_transaction/);
  assert.doesNotMatch(route, /from\("tasks"\)\.insert/);
  assert.match(transactionalCreationMigration, /create or replace function public\.create_task_transaction/);
  assert.match(transactionalCreationMigration, /insert into public\.task_relationship_edges/);
  assert.match(transactionalCreationMigration, /insert into public\.notification_events/);
  assert.match(transactionalCreationMigration, /insert into public\.audit_log/);
  assert.match(transactionalCreationMigration, /tasks_creation_request_id_unique_idx/);
  assert.match(transactionalCreationMigration, /pg_advisory_xact_lock\(hashtextextended\('task-create:'/);
  assert.match(transactionalCreationMigration, /'replayed', true/);
  assert.match(route, /creationRequestId/);
  assert.match(createCommand, /setTaskDialogDefaults\(null\)/);
  assert.match(createCommand, /if \(!response\.ok \|\| !body\?\.task\)/);
  assert.match(route, /Founder können nur eigene Deliverables verfeinern/);
  assert.match(route, /taskType === "deliverable"/);
  assert.match(route, /taskType === "proposal" \? null/);
  assert.match(route, /Deliverables brauchen Initiative und Sprint/);
  assert.match(updateRoute, /shouldPromoteProposal/);
  assert.match(updateRoutePolicy, /currentTask\.task_type === "proposal"/);
  assert.match(updateRoutePolicy, /effectiveStatus !== "Vorschlag"/);
  assert.match(updateRoute, /update\.task_type = "deliverable"/);
  assert.match(updateRoute, /update\.score_relevant = true/);
  assert.match(promotionMigration, /task_type = 'proposal'/);
  assert.match(promotionMigration, /status <> 'Vorschlag'/);
  assert.match(route, /deadline: payload\.deadline/);
  assert.match(route, /Das Startdatum darf nicht nach dem Enddatum liegen/);
  assert.match(updateRoutePolicy, /Nur Vorschläge können ohne Zuständigkeit bleiben/);
  assert.match(ui, /NewTaskDialog/);
  assert.match(display, /Nicht zugeordnet/);
  assert.match(newTaskUi, /Vorschläge können bewusst ohne Zuständigkeit bleiben/);
  assert.match(newTaskUi, /taskAssigneeOptions\(draft\.taskType, data\.profiles\)/);
  assert.match(newTaskUi, /Sub-Issues/);
  assert.match(newTaskUi, /werden nicht bewertet/);
  assert.match(newTaskUi, /Zusätzlich extern anlegen/);
  assert.match(newTaskUi, /createGitHubIssue/);
  assert.match(newTaskUi, /Wird erstellt\.\.\./);
  assert.match(newTaskUi, /globalThis\.crypto\.randomUUID\(\)/);
  assert.match(newTaskUi, /relationType/);
  assert.match(newTaskUi, /relatedTaskId/);
  assert.match(newTaskUi, /Zieltermin/);
  assert.match(ui, /createIfMissing: true/);
  assert.match(types, /TaskType = "deliverable" \| "proposal" \| "sub_issue"/);
});

test("weekly meeting attendance has scoring, absence reasons and updates", async () => {
  const migration = await readFile("supabase/0007_meeting_attendance_scoring.sql", "utf8");
  const route = await readFile("src/app/api/meetings/[id]/attendance/route.ts", "utf8");
  const data = await readFile("src/lib/planning-data-loader.ts", "utf8");
  const sprintUi = await readFeatureSurface("src/features/sprint");
  const sprintMeetingUi = await readFile("src/features/sprint/molecules/sprint-meeting-attendance-section.tsx", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");

  assert.match(migration, /create table if not exists meetings/);
  assert.match(migration, /create table if not exists meeting_attendance/);
  assert.match(migration, /reason_accepted/);
  assert.match(migration, /written_update/);
  assert.match(route, /meeting\.attendance_updated/);
  assert.match(route, /Founder können nur ihre eigene Weekly-Rückmeldung ändern/);
  assert.match(route, /Nur CEO oder Deputy können Anwesenheit final bewerten/);
  assert.match(route, /founderSelfReportStatuses/);
  assert.match(route, /founder_self_report/);
  assert.match(route, /lead_review/);
  assert.match(data, /meetingAttendance/);
  assert.match(sprintUi, /SprintMeetingAttendanceSection/);
  assert.match(sprintMeetingUi, /Weekly Updates/);
  assert.match(sprintMeetingUi, /max\. 2 je Weekly, 4 je Sprint/);
  assert.match(sprintMeetingUi, /Triftiger Grund/);
  assert.match(sprintMeetingUi, /eigene Rückmeldung/);
  assert.match(sprintMeetingUi, /canScoreAttendance/);
  assert.match(sprintMeetingUi, /\[0, 1, 2\]/);
  assert.match(types, /MeetingAttendanceStatus/);
});

test("meeting finder, calendar sync and decision log surfaces are removed while weekly score storage remains", async () => {
  const ui = await readPlanningSurface();
  const sidebar = await readFile("src/features/planning/organisms/app-sidebar.tsx", "utf8");
  const verify = await readFile("scripts/verify-supabase.mjs", "utf8");
  const schemaChecks = await readFile("src/lib/planning-schema-checks.json", "utf8");
  const schema = await readFile("supabase/schema.sql", "utf8");
  const cleanupMigration = await readFile("supabase/0038_remove_meeting_finder_decision_log.sql", "utf8");
  const planningApiClient = await readFile("src/features/planning/model/planning-api-client.ts", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");

  assert.doesNotMatch(ui, /MeetingFinderOverview|DecisionLogOverview/);
  assert.doesNotMatch(sidebar, /Meeting Finder|Decision Log/);
  assert.doesNotMatch(planningApiClient, /createMeetingRequest|availabilityRequest|syncGoogleCalendarRequest|createDecisionRequest/);
  assert.match(verify, /planning-schema-checks\.json/);
  assert.doesNotMatch(schemaChecks, /availability\.calendar_sync|meetings\.google_calendar_sync|profiles\.google_calendar|decision_task_links/);
  assert.match(schemaChecks, /meetings\.weekly_score/);
  assert.match(schema, /create table if not exists meetings/);
  assert.match(schema, /create table if not exists meeting_attendance/);
  assert.doesNotMatch(schema, /google_calendar|decision_task_links/);
  assert.match(types, /meetings: Meeting\[\]/);
  assert.match(types, /meetingAttendance: MeetingAttendance\[\]/);
  assert.doesNotMatch(types, /export type AvailabilityEntry|export type DecisionTaskLink|export type Decision/);
  assert.match(cleanupMigration, /drop table if exists availability cascade/);
  assert.match(cleanupMigration, /drop table if exists decision_log cascade/);
  assert.match(cleanupMigration, /drop column if exists google_calendar_email/);
  assert.match(cleanupMigration, /default_workspace = 'meetings' then 'sprint'/);
  assert.match(cleanupMigration, /default_workspace = 'decisions' then 'planning'/);
});
