import { readFile } from "node:fs/promises";
import { readFeatureSurface, readPlanningSurface } from "./helpers/planning-surface.mjs";
import test from "node:test";
import assert from "node:assert/strict";

test("fmd tools hub keeps internal tools repos notion and drive visible", async () => {
  const migration = await readFile("supabase/0015_fmd_tools_hub.sql", "utf8");
  const ui = await readPlanningSurface();
  const toolsUi = await readFile("src/features/tools/organisms/fmd-tools-overview.tsx", "utf8");
  const data = await readFile("src/lib/planning-data-loader.ts", "utf8");
  const seed = await readFile("src/lib/seed/source.json", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");

  assert.match(migration, /create table if not exists fmd_tools/);
  assert.match(migration, /email-signature-tool/);
  assert.match(migration, /https:\/\/mailsig\.findmydoc\.eu\//);
  assert.match(migration, /'email-signature-tool'.*'active'/s);
  assert.match(migration, /investor-calculator/);
  assert.match(migration, /notion-docs-source/);
  assert.match(migration, /https:\/\/www\.notion\.so\/Team-Workspace-31c283c73e6180cf9eedc8e0694cf2db/);
  assert.match(migration, /google-drive-assets/);
  assert.match(migration, /https:\/\/drive\.google\.com\/drive\/shared-drives/);
  const pitchdeckMigration = await readFile("supabase/0021_pitchdeck_tool.sql", "utf8");
  assert.match(pitchdeckMigration, /pitchdeck-site/);
  assert.match(pitchdeckMigration, /https:\/\/pitchdeck\.findmydoc\.eu\//);
  assert.match(ui, /FmdToolsOverview/);
  assert.match(toolsUi, /FMD-Tools Hub/);
  assert.match(toolsUi, /Interne Tools/);
  assert.match(data, /fmdTools/);
  assert.match(seed, /https:\/\/mailsig\.findmydoc\.eu\//);
  assert.match(seed, /https:\/\/www\.notion\.so\/Team-Workspace-31c283c73e6180cf9eedc8e0694cf2db/);
  assert.match(seed, /https:\/\/pitchdeck\.findmydoc\.eu\//);
  assert.match(seed, /https:\/\/drive\.google\.com\/drive\/shared-drives/);
  assert.match(types, /export type FmdTool/);
});

test("execution layer adds focus board hygiene alerts and decision task links", async () => {
  const migration = await readFile("supabase/0020_execution_layer.sql", "utf8");
  const ui = await readPlanningSurface();
  const executionUi = await readFeatureSurface("src/features/execution");
  const executionViewModel = await readFile("src/features/execution/model/execution-layer-view-model.ts", "utf8");
  const decisionUi = await readFeatureSurface("src/features/decisions");
  const sidebar = await readFile("src/features/planning/organisms/app-sidebar.tsx", "utf8");
  const data = await readFile("src/lib/planning-data-loader.ts", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");
  const focusRoute = await readFile("src/app/api/focus/route.ts", "utf8");
  const decisionTaskRoute = await readFile("src/app/api/decisions/[id]/tasks/route.ts", "utf8");
  const planningApiClient = await readFile("src/features/planning/model/planning-api-client.ts", "utf8");
  const verify = await readFile("scripts/verify-supabase.mjs", "utf8");
  const health = await readFile("src/app/api/health/route.ts", "utf8");
  const schema = await readFile("supabase/schema.sql", "utf8");
  const detail = await readFile("src/features/tasks/templates/task-detail-page.tsx", "utf8");
  const taskContext = await readFile("src/features/tasks/molecules/task-context-section.tsx", "utf8");
  const taskPage = await readFile("src/app/tasks/[id]/page.tsx", "utf8");
  const agents = await readFile("AGENTS.md", "utf8");
  const plan = await readFile("docs/execution-layer-plan.md", "utf8");

  assert.match(migration, /create table if not exists task_focus_items/);
  assert.match(migration, /create table if not exists decision_task_links/);
  assert.match(migration, /unique \(profile_id, task_id, focus_date\)/);
  assert.match(migration, /unique \(decision_id, task_id\)/);
  assert.match(sidebar, /Execution/);
  assert.match(ui, /ExecutionLayerOverview/);
  assert.match(executionUi, /Heute-Fokus/);
  assert.match(executionUi, /Meine Reviews/);
  assert.match(executionUi, /Team-Reviews/);
  assert.match(executionUi, /Ohne Review Owner/);
  assert.match(executionViewModel, /myReviewTasks/);
  assert.match(executionViewModel, /teamReviewTasks/);
  assert.match(executionUi, /Hygiene Alerts/);
  assert.match(executionUi, /Decision-Folgearbeit/);
  assert.match(executionUi, /followUpCounts/);
  assert.match(executionUi, /Folgearbeit offen/);
  assert.match(executionUi, /Folgeaufgabe aus Decision/);
  assert.match(ui, /Folgeaufgabe aus Decision Log/);
  assert.match(decisionUi, /Folgeaufgaben/);
  assert.match(ui, /onCreateFollowUp/);
  assert.match(executionUi, /In Fokus/);
  assert.match(executionUi, /onRemoveFocus/);
  assert.match(executionUi, /onRemoveDecisionTaskLink/);
  assert.match(executionUi, /Alle Schweregrade/);
  assert.match(executionUi, /Alle Bereiche/);
  assert.match(executionUi, /Kritische Alerts/);
  assert.match(executionUi, /Team-Fokus gesetzt/);
  assert.match(executionUi, /Team-Fokus heute/);
  assert.match(executionUi, /Mein Fokus heute/);
  assert.match(executionUi, /buildExecutionLayerViewModel/);
  assert.match(executionViewModel, /executionTasks = isOperationalLead/);
  assert.match(executionViewModel, /executionTaskIds/);
  assert.match(executionViewModel, /item\.profileId === currentProfile\?\.id/);
  assert.match(executionViewModel, /taskBelongsToProfile\(task, currentProfile\)/);
  assert.match(executionUi, /Fokus-Verlauf/);
  assert.match(executionUi, /Tagesabschluss/);
  assert.match(executionUi, /Abschlussquote/);
  assert.match(executionUi, /Als erledigt markieren/);
  assert.match(executionViewModel, /endOfDayCompletion/);
  assert.match(executionViewModel, /teamFocusCoverage/);
  assert.match(executionViewModel, /focusHistoryByDate/);
  assert.match(executionUi, /Offene verschieben/);
  assert.match(executionViewModel, /executionMetrics/);
  assert.match(executionUi, /Decision-Link entfernen/);
  assert.match(executionUi, /decisionId/);
  assert.match(executionUi, /decisionLinkNote/);
  assert.match(planningApiClient, /api\/decisions\/\$\{decisionId\}\/tasks/);
  assert.match(ui, /buildHygieneAlerts/);
  assert.match(executionUi, /recommendedAction/);
  assert.match(executionUi, /Nächste Aktion/);
  assert.match(executionUi, /Aktion in Fokus/);
  assert.match(focusRoute, /Founder können nur eigene Aufgaben in den Fokus nehmen/);
  assert.match(focusRoute, /Founder können nur eigene Fokus-Einträge entfernen/);
  assert.match(ui, /Acceptance Criteria fehlen/);
  assert.match(ui, /Decision ohne Folgeaufgabe/);
  const panel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  const panelContext = await readFile("src/features/tasks/molecules/task-detail-panel-context-section.tsx", "utf8");
  assert.match(panel, /TaskDetailPanelContextSection/);
  assert.match(panelContext, /Begründende Decisions/);
  assert.match(panelContext, /Fokus-Kontext/);
  assert.match(detail, /TaskContextSection/);
  assert.match(taskContext, /Begründende Decisions/);
  assert.match(taskContext, /Fokus-Kontext/);
  assert.match(detail, /focusItems/);
  assert.match(detail, /decisionTaskLinks/);
  assert.match(taskPage, /focusItems=\{data\.taskFocusItems\}/);
  assert.match(taskPage, /decisionTaskLinks=\{data\.decisionTaskLinks\}/);
  assert.match(data, /taskFocusItems/);
  assert.match(data, /decisionTaskLinks/);
  assert.match(types, /export type TaskFocusItem/);
  assert.match(types, /export type DecisionTaskLink/);
  assert.match(focusRoute, /task_focus_items/);
  assert.match(focusRoute, /Heute-Fokus ist auf drei Aufgaben begrenzt/);
  assert.match(focusRoute, /export async function DELETE/);
  assert.match(focusRoute, /Fokus entfernt/);
  assert.match(focusRoute, /Fokus aktualisiert/);
  assert.match(decisionTaskRoute, /decision_task_links/);
  assert.match(decisionTaskRoute, /export async function DELETE/);
  assert.match(decisionTaskRoute, /Decision-Verknüpfung entfernt/);
  assert.match(decisionTaskRoute, /Mit Decision verknüpft/);
  assert.match(verify, /task_focus_items/);
  assert.match(verify, /decision_task_links/);
  assert.match(health, /task_focus_items/);
  assert.match(health, /decision_task_links/);
  assert.match(schema, /create table if not exists task_focus_items/);
  assert.match(schema, /create table if not exists decision_task_links/);
  assert.match(agents, /docs\/execution-layer-plan\.md/);
  assert.match(plan, /Focus Board \/ Heute-Modus/);
  assert.match(plan, /Aging & Hygiene Alerts/);
  assert.match(plan, /Decision-to-Task Links/);
});

test("task creation supports deliverables proposals and non scoring sub issues", async () => {
  const migration = await readFile("supabase/0006_task_creation_hierarchy.sql", "utf8");
  const route = await readFile("src/app/api/tasks/route.ts", "utf8");
  const updateRoute = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const updateRouteHelpers = await readFile("src/features/tasks/model/task-route-update-helpers.ts", "utf8");
  const updateRoutePolicy = `${updateRoute}\n${updateRouteHelpers}`;
  const promotionMigration = await readFile("supabase/0034_promote_assigned_proposals.sql", "utf8");
  const ui = await readPlanningSurface();
  const newTaskUi = await readFile("src/features/tasks/organisms/new-task-dialog.tsx", "utf8");
  const display = await readFile("src/lib/display.ts", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");

  assert.match(migration, /task_type/);
  assert.match(migration, /parent_task_id/);
  assert.match(migration, /score_relevant/);
  assert.match(route, /task\.proposed/);
  assert.match(route, /Founder können nur eigene Deliverables verfeinern/);
  assert.match(route, /taskType === "deliverable"/);
  assert.match(route, /taskType === "proposal" \? null/);
  assert.match(route, /Deliverables brauchen Initiative und Sprint/);
  assert.match(updateRoute, /shouldPromoteProposal/);
  assert.match(updateRoutePolicy, /currentTask\.task_type === "proposal"/);
  assert.match(updateRoutePolicy, /effectiveStatus !== "Vorschlag"/);
  assert.match(updateRoute, /update\.task_type = "deliverable"/);
  assert.match(updateRoute, /update\.score_relevant = true/);
  assert.match(promotionMigration, /task_type = 'proposal'/);
  assert.match(promotionMigration, /status <> 'Vorschlag'/);
  assert.match(route, /deadline: payload\.deadline/);
  assert.match(route, /Das Startdatum darf nicht nach dem Enddatum liegen/);
  assert.match(updateRoutePolicy, /Nur Vorschläge können ohne Assignee bleiben/);
  assert.match(ui, /NewTaskDialog/);
  assert.match(display, /Nicht zugeordnet/);
  assert.match(newTaskUi, /Vorschläge können bewusst ohne Assignee bleiben/);
  assert.match(newTaskUi, /taskOwnerOptions\(draft\.taskType, data\.profiles\)/);
  assert.match(newTaskUi, /Sub-Issues/);
  assert.match(newTaskUi, /nicht score-relevant/);
  assert.match(newTaskUi, /Direkt als GitHub-Issue anlegen/);
  assert.match(newTaskUi, /createGitHubIssue/);
  assert.match(newTaskUi, /relationType/);
  assert.match(newTaskUi, /relatedTaskId/);
  assert.match(newTaskUi, /Zieltermin/);
  assert.match(ui, /createIfMissing: true/);
  assert.match(types, /TaskType = "deliverable" \| "proposal" \| "sub_issue"/);
});

test("weekly meeting attendance has scoring, absence reasons and updates", async () => {
  const migration = await readFile("supabase/0007_meeting_attendance_scoring.sql", "utf8");
  const route = await readFile("src/app/api/meetings/[id]/attendance/route.ts", "utf8");
  const data = await readFile("src/lib/planning-data-loader.ts", "utf8");
  const sprintUi = await readFeatureSurface("src/features/sprint");
  const sprintMeetingUi = await readFile("src/features/sprint/molecules/sprint-meeting-attendance-section.tsx", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");

  assert.match(migration, /create table if not exists meetings/);
  assert.match(migration, /create table if not exists meeting_attendance/);
  assert.match(migration, /reason_accepted/);
  assert.match(migration, /written_update/);
  assert.match(route, /meeting\.attendance_updated/);
  assert.match(route, /Founder können nur ihre eigene Meeting-Rückmeldung ändern/);
  assert.match(route, /Nur CEO oder Deputy können Anwesenheit final bewerten/);
  assert.match(route, /founderSelfReportStatuses/);
  assert.match(route, /founder_self_report/);
  assert.match(route, /lead_review/);
  assert.match(data, /meetingAttendance/);
  assert.match(sprintUi, /SprintMeetingAttendanceSection/);
  assert.match(sprintMeetingUi, /Weekly Updates/);
  assert.match(sprintMeetingUi, /max\. 2 je Weekly, 4 je Sprint/);
  assert.match(sprintMeetingUi, /Triftiger Grund/);
  assert.match(sprintMeetingUi, /eigene Rückmeldung/);
  assert.match(sprintMeetingUi, /canScoreAttendance/);
  assert.match(sprintMeetingUi, /\[0, 1, 2\]/);
  assert.match(types, /MeetingAttendanceStatus/);
});

test("meeting finder manages working hours blockers and guarded availability", async () => {
  const route = await readFile("src/app/api/availability/route.ts", "utf8");
  const meetingRoute = await readFile("src/app/api/meetings/route.ts", "utf8");
  const calendarRoute = await readFile("src/app/api/calendar-sync/route.ts", "utf8");
  const calendarLib = await readFile("src/lib/google-calendar.ts", "utf8");
  const ui = await readPlanningSurface();
  const meetingUi = await readFeatureSurface("src/features/meetings");
  const meetingLogic = await readFile("src/features/meetings/model/meeting-finder.ts", "utf8");
  const meetingOptions = await readFile("src/features/meetings/model/meeting-options.ts", "utf8");
  const meetingViewModel = await readFile("src/features/meetings/model/meeting-finder-view-model.ts", "utf8");
  const meetingAvailabilityHook = await readFile("src/features/meetings/hooks/use-meeting-availability-editor.ts", "utf8");
  const availabilityDialogUi = await readFile("src/features/meetings/organisms/meeting-availability-dialog.tsx", "utf8");
  const availabilityFormsUi = await readFile("src/features/meetings/molecules/meeting-availability-forms.tsx", "utf8");
  const availabilitySummaryUi = await readFile("src/features/meetings/molecules/meeting-availability-summary-section.tsx", "utf8");
  const calendarMonthUi = await readFile("src/features/meetings/organisms/meeting-calendar-month-view.tsx", "utf8");
  const calendarToolbarUi = await readFile("src/features/meetings/molecules/meeting-calendar-toolbar.tsx", "utf8");
  const calendarWeekUi = await readFile("src/features/meetings/organisms/meeting-calendar-week-view.tsx", "utf8");
  const slotSearchUi = await readFile("src/features/meetings/organisms/meeting-slot-search-section.tsx", "utf8");
  const plannedMeetingsUi = await readFile("src/features/meetings/organisms/planned-meetings-section.tsx", "utf8");
  const migration = await readFile("supabase/0002_founder_platform.sql", "utf8");
  const calendarMigration = await readFile("supabase/0022_meeting_finder_calendar_sync.sql", "utf8");
  const profileCalendarMigration = await readFile("supabase/0023_google_calendar_profile_sync.sql", "utf8");
  const blockerDetailsMigration = await readFile("supabase/0024_availability_blocker_details.sql", "utf8");
  const meetingCalendarMigration = await readFile("supabase/0025_meeting_calendar_sync.sql", "utf8");
  const customDurationMigration = await readFile("supabase/0026_meeting_custom_duration.sql", "utf8");
  const verify = await readFile("scripts/verify-supabase.mjs", "utf8");

  assert.match(migration, /create table if not exists availability/);
  assert.match(calendarMigration, /source in \('manual', 'google_calendar'\)/);
  assert.match(calendarMigration, /availability_google_external_idx/);
  assert.match(profileCalendarMigration, /google_calendar_email/);
  assert.match(profileCalendarMigration, /google_calendar_sync_enabled/);
  assert.match(blockerDetailsMigration, /title text/);
  assert.match(blockerDetailsMigration, /blocker_kind/);
  assert.match(blockerDetailsMigration, /customer_appointment/);
  assert.match(meetingCalendarMigration, /duration_minutes/);
  assert.match(meetingCalendarMigration, /google_calendar_event_id/);
  assert.match(meetingCalendarMigration, /meetings_write_team/);
  assert.match(customDurationMigration, /between 15 and 480/);
  assert.match(verify, /availability\.calendar_sync/);
  assert.match(verify, /blocker_kind/);
  assert.match(verify, /meetings\.google_calendar_sync/);
  assert.match(verify, /profiles\.google_calendar/);
  assert.match(route, /requireFounder/);
  assert.match(route, /Founder können nur eigene Verfügbarkeiten pflegen/);
  assert.match(route, /source: "manual"/);
  assert.match(route, /external_calendar_id/);
  assert.match(route, /blockerKind/);
  assert.match(route, /availability\.create/);
  assert.match(route, /availability\.delete/);
  assert.match(route, /export async function PATCH/);
  assert.match(route, /availability\.update/);
  assert.match(route, /Google-Kalenderblöcke/);
  assert.match(meetingRoute, /requireOperationalLead/);
  assert.match(meetingRoute, /requireFounder/);
  assert.match(meetingRoute, /export async function PATCH/);
  assert.match(meetingRoute, /meeting_attendance/);
  assert.match(meetingRoute, /createGoogleCalendarEvent/);
  assert.match(meetingRoute, /durationMinutes/);
  assert.match(meetingRoute, /cleanDurationMinutes/);
  assert.match(meetingRoute, /meeting\.create/);
  assert.match(meetingRoute, /meeting\.update/);
  assert.match(meetingRoute, /meeting\.created/);
  assert.match(meetingRoute, /profileIds/);
  assert.match(calendarRoute, /requireOperationalLead/);
  assert.match(calendarRoute, /availability\.google_calendar_sync/);
  assert.match(calendarRoute, /google_calendar_sync_enabled/);
  assert.match(calendarRoute, /source: "google_calendar"/);
  assert.match(calendarRoute, /calendar_event/);
  assert.match(calendarRoute, /activeEventIds/);
  assert.match(calendarRoute, /staleIds/);
  assert.match(calendarRoute, /removed/);
  assert.match(calendarLib, /GOOGLE_SERVICE_ACCOUNT_EMAIL/);
  assert.match(calendarLib, /GOOGLE_SERVICE_ACCOUNT_KEY/);
  assert.match(calendarLib, /calendar\.events/);
  assert.doesNotMatch(calendarRoute, /console\.log/);
  assert.match(ui, /MeetingFinderOverview/);
  assert.match(meetingUi, /buildMeetingFinderViewModel/);
  assert.match(meetingUi, /useMeetingAvailabilityEditor/);
  assert.match(meetingLogic, /findMeetingSlots/);
  assert.match(meetingViewModel, /findMeetingSlots/);
  assert.match(meetingViewModel, /buildMeetingFinderDefaults/);
  assert.match(meetingLogic, /calendarBlockPosition/);
  assert.match(meetingLogic, /summarizeCalendarDay/);
  assert.match(meetingLogic, /buildCalendarCell/);
  assert.match(meetingLogic, /buildCalendarBlocksForDate/);
  assert.match(meetingUi, /MeetingSlotSearchSection/);
  assert.match(slotSearchUi, /customDuration/);
  assert.match(slotSearchUi, /searchStartTime/);
  assert.match(slotSearchUi, /Früheste Startzeit wählen/);
  assert.match(slotSearchUi, /Eigene Dauer/);
  assert.match(meetingLogic, /meetingOverlapsSlot/);
  assert.match(meetingUi, /MeetingAvailabilityForms/);
  assert.match(meetingUi, /MeetingAvailabilityDialog/);
  assert.match(meetingUi, /MeetingAvailabilitySummarySection/);
  const availabilityFieldUi = `${availabilityFormsUi}\n${availabilityDialogUi}\n${await readFile("src/features/meetings/molecules/meeting-blocker-form-fields.tsx", "utf8")}`;
  assert.match(availabilityFormsUi, /Arbeitszeiten pflegen/);
  assert.match(availabilityFormsUi, /Mo-Fr auswählen/);
  assert.match(meetingAvailabilityHook, /toggleWorkWeekday/);
  assert.match(meetingAvailabilityHook, /addWorkingHours/);
  assert.match(availabilityFormsUi, /Arbeitszeiten für/);
  assert.match(availabilityFormsUi, /Blocker eintragen/);
  assert.match(availabilityFieldUi, /Art des Blockers/);
  assert.match(availabilityFieldUi, /Blocker-Titel/);
  assert.match(meetingOptions, /Kundentermin/);
  assert.match(meetingAvailabilityHook, /availabilityTypeForBlockerKind/);
  assert.match(meetingAvailabilityHook, /blockerKindForAvailability/);
  assert.match(availabilityFieldUi, /Ganztägig blockieren/);
  assert.match(slotSearchUi, /Google Workspace Sync/);
  assert.match(slotSearchUi, /Google-Kalender synchronisieren/);
  assert.match(slotSearchUi, /Google-Termin öffnen/);
  assert.match(slotSearchUi, /In App anlegen/);
  assert.match(slotSearchUi, /Meeting vormerken/);
  assert.match(plannedMeetingsUi, /Intern vormerken/);
  assert.match(meetingUi, /MeetingCalendarMonthView/);
  assert.match(meetingUi, /MeetingCalendarToolbar/);
  assert.match(meetingUi, /MeetingCalendarWeekView/);
  assert.match(calendarToolbarUi, /Kalenderansicht/);
  assert.match(meetingUi, /calendarCellFor/);
  assert.match(meetingUi, /calendarDaySummary/);
  assert.match(meetingUi, /moveCalendar/);
  assert.match(meetingLogic, /availabilitySummaryTone/);
  assert.match(calendarToolbarUi, /Wochenraster wie im Kalender/);
  assert.match(calendarToolbarUi, /Monatsübersicht/);
  assert.match(calendarToolbarUi, /Kalenderansicht wählen/);
  assert.match(calendarToolbarUi, /Schraffierte Flächen/);
  assert.match(calendarMonthUi, /month-cell/);
  assert.match(calendarMonthUi, /Nicht verfügbar/);
  assert.match(calendarMonthUi, /blockiert/);
  assert.match(calendarMonthUi, /Meeting/);
  assert.match(calendarWeekUi, /GMT\+02/);
  assert.match(calendarWeekUi, /Blocker anlegen/);
  assert.match(calendarWeekUi, /Arbeitszeit ohne Blocker/);
  assert.match(calendarWeekUi, /calendarBlockPosition/);
  assert.match(meetingUi, /availabilityDialogMode/);
  assert.match(meetingUi, /beginCalendarSelection/);
  assert.match(meetingUi, /calendarDrag/);
  assert.match(meetingUi, /beginCalendarBlockDrag/);
  assert.match(meetingUi, /finishCalendarBlockDrag/);
  assert.match(meetingUi, /openAvailabilityEditDialog/);
  assert.match(meetingUi, /onUpdateAvailability/);
  assert.match(availabilityDialogUi, /Blocker bearbeiten/);
  assert.match(availabilityDialogUi, /Blocker speichern/);
  assert.match(availabilityDialogUi, /Dialog schließen/);
  assert.doesNotMatch(meetingUi, /Alle frei/);
  assert.doesNotMatch(meetingUi, /Teilweise frei/);
  assert.match(meetingUi, /calendarWeekStart/);
  assert.match(meetingLogic, /startOfWeekKey/);
  assert.match(meetingViewModel, /calendarMonthLabel/);
  assert.match(calendarToolbarUi, /Mein Kalender/);
  assert.match(calendarToolbarUi, /Alle anzeigen/);
  assert.match(plannedMeetingsUi, /Vorgemerkte Meetings/);
  assert.match(plannedMeetingsUi, /Meeting absagen/);
  assert.match(plannedMeetingsUi, /attendanceForMeeting/);
  assert.match(meetingLogic, /meetingSlotIso/);
  assert.match(meetingViewModel, /googleCalendarEmail/);
  assert.match(availabilitySummaryUi, /Kalenderwoche & Blocker/);
  assert.match(availabilitySummaryUi, /Keine Einträge/);
  assert.match(availabilitySummaryUi, /Kalenderstatus/);
  assert.match(availabilitySummaryUi, /onDeleteAvailability/);
  assert.match(slotSearchUi, /Keine passenden Slots/);
  assert.match(slotSearchUi, /CustomDatePicker/);
  assert.match(slotSearchUi, /CustomSelect/);
});
