import { readFile } from "node:fs/promises";
import test from "node:test";
import assert from "node:assert/strict";

test("task route opens the detail panel inside the planning shell", async () => {
  const route = await readFile("src/app/tasks/[id]/page.tsx", "utf8");
  const page = await readFile("src/components/task-detail-page.tsx", "utf8");
  const ui = await readFile("src/components/planning-app.tsx", "utf8");
  const panel = await readFile("src/components/task-detail-panel.tsx", "utf8");
  const panelBlockerSection = await readFile("src/components/task-detail-panel-blocker-section.tsx", "utf8");
  const panelHeader = await readFile("src/components/task-detail-panel-header.tsx", "utf8");
  const panelBriefSection = await readFile("src/components/task-detail-panel-brief-section.tsx", "utf8");
  const panelContextSection = await readFile("src/components/task-detail-panel-context-section.tsx", "utf8");
  const panelDependenciesSection = await readFile("src/components/task-detail-panel-dependencies-section.tsx", "utf8");
  const panelSubIssuesSection = await readFile("src/components/task-detail-panel-sub-issues-section.tsx", "utf8");
  const panelNotesSection = await readFile("src/components/task-detail-panel-notes-section.tsx", "utf8");
  const panelSidebarSection = await readFile("src/components/task-detail-panel-sidebar.tsx", "utf8");
  const subIssuesSection = await readFile("src/components/task-sub-issues-section.tsx", "utf8");
  const commentHook = await readFile("src/hooks/use-task-comments.ts", "utf8");
  const brand = await readFile("src/components/app-brand.tsx", "utf8");
  const sidebar = await readFile("src/components/app-sidebar.tsx", "utf8");

  assert.match(route, /getPlanningData/);
  assert.match(route, /PlanningApp/);
  assert.match(route, /TaskDetailPage/);
  assert.match(route, /view === "full"/);
  assert.match(route, /initialTaskId=\{id\}/);
  assert.match(ui, /initialTaskId/);
  assert.match(ui, /useSearchParams/);
  assert.match(ui, /fullTaskView/);
  assert.match(ui, /searchParams\.get\("view"\) === "full"/);
  assert.match(ui, /openTaskPanel/);
  assert.match(ui, /router\.push\(`\/tasks\/\$\{encodeURIComponent\(taskId\)\}`\)/);
  assert.match(ui, /openReviewSheet/);
  assert.match(ui, /reviewTask=\$\{encodeURIComponent\(task\.id\)\}/);
  assert.match(ui, /#accountable-review-sheet/);
  assert.match(ui, /router\.back\(\)/);
  assert.match(ui, /event\.key !== "Backspace"/);
  assert.match(ui, /TaskDetailPanel/);
  assert.match(ui, /<TaskDetailPage/);
  assert.match(panel, /bg-slate-950\/\[0\.03\]/);
  assert.match(panel, /TaskDetailPanelHeader/);
  assert.match(panelHeader, /aria-label="Detailpanel schließen"/);
  assert.match(panelHeader, /Große Ansicht/);
  assert.match(panelHeader, /view=full/);
  assert.match(panelHeader, /statusTone/);
  assert.match(panelHeader, /priorityTone/);
  const taskDetailPanel = panel.slice(panel.indexOf("export function TaskDetailPanel"));
  assert.match(taskDetailPanel, /TaskDetailPanelBriefSection/);
  assert.match(panelBriefSection, /Aufgabenbrief/);
  assert.ok(panelBriefSection.indexOf("Problem Statement") < panelBriefSection.indexOf("Intended Outcome"));
  assert.ok(panelBriefSection.indexOf("Intended Outcome") < panelBriefSection.indexOf("Scope & Constraints"));
  assert.ok(panelBriefSection.indexOf("Scope & Constraints") < panelBriefSection.indexOf("Acceptance Criteria"));
  assert.ok(panelBriefSection.indexOf("Acceptance Criteria") < panelBriefSection.indexOf("Evidence Required"));
  assert.ok(panelBriefSection.indexOf("Evidence Required") < panelBriefSection.indexOf("Definition of Done"));
  assert.match(taskDetailPanel, /TaskDetailPanelContextSection/);
  assert.match(panelContextSection, /Fokus-Kontext/);
  assert.match(panelContextSection, /Begründende Decisions/);
  assert.match(panelContextSection, /decisionStatusLabel/);
  assert.match(panelContextSection, /Kein nächster Schritt hinterlegt/);
  assert.ok(taskDetailPanel.indexOf("TaskDetailPanelBriefSection") < taskDetailPanel.indexOf("TaskDetailPanelContextSection"));
  assert.match(taskDetailPanel, /TaskDetailPanelDependenciesSection/);
  assert.match(panelDependenciesSection, /Abhängigkeiten & Evidence/);
  assert.match(panelDependenciesSection, /RelationshipList/);
  assert.match(panelDependenciesSection, /CommentBody/);
  assert.match(panelDependenciesSection, /Relationship hinzufügen/);
  assert.match(taskDetailPanel, /TaskDetailPanelSubIssuesSection/);
  assert.match(panelSubIssuesSection, /Sub-Issues/);
  assert.match(panelSubIssuesSection, /Noch keine Sub-Issues/);
  assert.match(panelSubIssuesSection, /taskOwnerLabel/);
  assert.match(taskDetailPanel, /TaskDetailPanelBlockerSection/);
  assert.match(panelBlockerSection, /Blocker früh melden/);
  assert.match(panelBlockerSection, /Blocker melden/);
  assert.match(panelBlockerSection, /Noch kein Blocker gemeldet/);
  assert.ok(taskDetailPanel.indexOf("TaskDetailPanelBlockerSection") < taskDetailPanel.indexOf("TaskCommentThread"));
  assert.match(taskDetailPanel, /TaskDetailPanelNotesSection/);
  assert.match(panelNotesSection, /Notizen/);
  assert.match(panelNotesSection, /Interne Notiz, Entscheidung oder nächster Schritt/);
  assert.match(taskDetailPanel, /TaskDetailPanelSidebar/);
  assert.ok(taskDetailPanel.indexOf("TaskDetailPanelSidebar") < taskDetailPanel.indexOf("TaskCommentThread"));
  assert.match(taskDetailPanel, /<div className="p-5">/);
  assert.match(taskDetailPanel, /<div className="mt-5 min-w-0">\s*<TaskCommentThread/);
  assert.doesNotMatch(taskDetailPanel, /lg:col-span-2/);
  assert.match(panelSidebarSection, /Steuerung/);
  assert.match(panelSidebarSection, /Planung/);
  assert.match(panelSidebarSection, /Review & Historie/);
  assert.match(panelSidebarSection, /Review Owner/);
  assert.match(panelSidebarSection, /canManageReviewOwner/);
  assert.match(panelSidebarSection, /onUpdate\(\{ reviewOwnerProfileId: value \}\)/);
  assert.match(panelSidebarSection, /Nur CEO kann den Review Owner ändern/);
  assert.match(panelSidebarSection, /Zum Review-Blatt/);
  assert.match(panelSidebarSection, /onOpenReview/);
  assert.match(panelSidebarSection, /Self-Review/);
  assert.match(panelSidebarSection, /GitHub/);
  assert.match(panelSidebarSection, /Aufgabe löschen/);
  assert.match(page, /title="Kommentare"/);
  assert.match(page, /<div className="mx-auto max-w-7xl px-6 py-6">/);
  assert.match(page, /<div className="mt-5 min-w-0">\s*<TaskCommentThread/);
  assert.doesNotMatch(page, /lg:col-span-2/);
  assert.match(page, /useTaskComments/);
  assert.match(commentHook, /api\/tasks\/\$\{task\.id\}\/comments/);
  assert.match(page, /AppSidebar/);
  assert.doesNotMatch(page, /detailNavItems/);
  assert.match(ui, /AppSidebar/);
  assert.match(sidebar, /appNavItems/);
  assert.match(sidebar, /Hauptnavigation/);
  assert.match(sidebar, /Meeting Finder/);
  assert.match(sidebar, /FMD-Tools/);
  assert.match(sidebar, /Sprint & Score/);
  assert.match(sidebar, /Decision Log/);
  assert.match(sidebar, /AppBrand/);
  assert.match(ui, /AppBrand/);
  assert.match(brand, /cross-mark\.svg/);
  assert.match(brand, /FounderOps/);
  assert.match(page, /Relationships/);
  assert.match(page, /TaskSubIssuesSection/);
  assert.ok(page.indexOf("TaskSubIssuesSection") < page.indexOf("title=\"Kommentare\""));
  assert.match(subIssuesSection, /Sub-Issues/);
  assert.match(subIssuesSection, /nicht score-relevant/);
});

test("task detail page supports github-like sidebar metadata and milestones", async () => {
  const migration = await readFile("supabase/0011_milestones_task_detail.sql", "utf8");
  const creatorMigration = await readFile("supabase/0017_task_created_by.sql", "utf8");
  const route = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const data = await readFile("src/lib/planning-data.ts", "utf8");
  const page = await readFile("src/components/task-detail-page.tsx", "utf8");
  const briefSection = await readFile("src/components/task-brief-section.tsx", "utf8");
  const contextSection = await readFile("src/components/task-context-section.tsx", "utf8");
  const detailsCard = await readFile("src/components/task-details-card.tsx", "utf8");
  const evidenceSection = await readFile("src/components/task-evidence-link-section.tsx", "utf8");
  const header = await readFile("src/components/task-detail-header.tsx", "utf8");
  const relationshipsSection = await readFile("src/components/task-relationships-section.tsx", "utf8");
  const subIssuesSection = await readFile("src/components/task-sub-issues-section.tsx", "utf8");
  const blockerCard = await readFile("src/components/task-blocker-card.tsx", "utf8");
  const detailGitHubSyncCard = await readFile("src/components/task-github-sync-card.tsx", "utf8");
  const taskDetailState = await readFile("src/lib/task-detail-state.ts", "utf8");
  const comments = await readFile("src/components/task-comment-thread.tsx", "utf8");
  const commentTimeline = await readFile("src/components/task-comment-timeline.tsx", "utf8");
  const app = await readFile("src/components/planning-app.tsx", "utf8");
  const panel = await readFile("src/components/task-detail-panel.tsx", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");
  const dataMappers = await readFile("src/lib/planning-data-mappers.ts", "utf8");

  assert.match(migration, /create table if not exists milestones/);
  assert.match(migration, /milestone_id/);
  assert.match(creatorMigration, /created_by text references profiles/);
  assert.match(route, /milestoneId/);
  assert.match(route, /packageId/);
  assert.match(route, /deadline/);
  assert.match(route, /dependsOn/);
  assert.match(route, /evidenceLink/);
  assert.match(route, /Diese Felder sind geschützt/);
  assert.match(route, /Founder können Aufgaben nur in Review geben/);
  assert.match(data, /milestones/);
  assert.match(dataMappers, /createdBy/);
  assert.match(types, /export type Milestone/);
  assert.match(types, /createdBy\?: string/);
  assert.match(page, /buildEditableTaskState/);
  assert.match(page, /buildTaskDetailGitHubState/);
  assert.match(page, /buildTaskDetailViewModel/);
  assert.match(page, /buildTaskDetailsDraft/);
  assert.match(page, /buildTaskBriefDraft/);
  assert.match(taskDetailState, /normalizeStatus/);
  assert.match(taskDetailState, /evidenceLink: task\.evidenceLink \|\| task\.issueUrl/);
  assert.match(taskDetailState, /buildTaskDetailGitHubState/);
  assert.match(taskDetailState, /buildTaskDetailsDraft/);
  assert.match(taskDetailState, /buildTaskBriefDraft/);
  assert.match(taskDetailState, /buildDetailsPackagePatch/);
  assert.match(taskDetailState, /buildDetailsMilestonePatch/);
  assert.match(taskDetailState, /taskRelationsFor/);
  assert.match(taskDetailState, /taskOwnerLabel/);
  assert.match(taskDetailState, /linkedFocusItems/);
  assert.match(taskDetailState, /relationTargetOptions/);
  assert.match(taskDetailState, /canManageTaskMeta/);
  assert.match(taskDetailState, /canSyncExistingGitHubIssue/);
  assert.match(page, /detailsEditing/);
  assert.match(page, /detailsEditSnapshot/);
  assert.match(page, /briefEditing/);
  assert.match(page, /TaskBriefSection/);
  assert.match(page, /TaskContextSection/);
  assert.match(page, /TaskDetailHeader/);
  assert.match(page, /TaskDetailsCard/);
  assert.match(page, /TaskEvidenceLinkSection/);
  assert.match(page, /TaskRelationshipsSection/);
  assert.match(page, /TaskSubIssuesSection/);
  assert.match(page, /TaskGitHubSyncCard/);
  assert.match(page, /TaskBlockerCard/);
  assert.match(briefSection, /Aufgabenbrief/);
  assert.match(briefSection, /Problem Statement/);
  assert.match(briefSection, /Acceptance Criteria/);
  assert.match(briefSection, /Definition of Done/);
  assert.match(briefSection, /TaskChecklist/);
  assert.match(briefSection, /onChecklistChange/);
  assert.match(contextSection, /Fokus-Kontext/);
  assert.match(contextSection, /Begründende Decisions/);
  assert.match(contextSection, /focusStatusLabel/);
  assert.match(contextSection, /Kein nächster Schritt hinterlegt/);
  assert.match(evidenceSection, /Evidence Link/);
  assert.match(evidenceSection, /onEvidenceLinkSave/);
  assert.match(evidenceSection, /CommentBody/);
  assert.match(header, /Zur Planung/);
  assert.match(header, /Aufgabendetail/);
  assert.match(header, /statusTone/);
  assert.match(header, /priorityTone/);
  assert.match(relationshipsSection, /Relationships/);
  assert.match(relationshipsSection, /Wartet auf/);
  assert.match(relationshipsSection, /Verknüpft mit/);
  assert.match(relationshipsSection, /onRelationDraftChange/);
  assert.match(relationshipsSection, /Legacy-Notiz/);
  assert.match(subIssuesSection, /Sub-Issues/);
  assert.match(subIssuesSection, /Noch keine Sub-Issues/);
  assert.match(subIssuesSection, /taskOwnerLabel/);
  assert.match(detailsCard, /Priorität/);
  assert.match(detailsCard, /Meilenstein/);
  assert.match(detailsCard, /Erstellt von/);
  assert.match(detailsCard, /Assignee/);
  assert.match(detailsCard, /canManageReviewOwner/);
  assert.match(detailsCard, /reviewOwnerProfileId/);
  assert.match(detailsCard, /Nur CEO kann den Review Owner ändern/);
  assert.match(detailsCard, /availableStatusOptions/);
  assert.match(detailsCard, /CustomDatePicker/);
  assert.match(detailsCard, /Bearbeiten/);
  assert.match(detailsCard, /onStatusChange/);
  assert.match(blockerCard, /Keine Blocker gemeldet/);
  assert.match(blockerCard, /openBlockerCount/);
  assert.match(detailGitHubSyncCard, /GitHub Sync/);
  assert.match(detailGitHubSyncCard, /Jetzt spiegeln/);
  assert.match(comments, /TaskCommentTimeline/);
  assert.match(commentTimeline, /github\.com\/\$\{login\}\.png/);
  assert.match(app, /TaskDetailPanel/);
  assert.match(panel, /TaskDetailPanelBriefSection/);
  assert.match(await readFile("src/components/task-detail-panel-brief-section.tsx", "utf8"), /TaskChecklist/);
  assert.match(await readFile("AGENTS.md", "utf8"), /Milestone management is a core workflow/);
});

test("planning hierarchy treats sprint as time container and packages as initiatives", async () => {
  const migration = await readFile("supabase/0013_epic_group_commitment_hierarchy.sql", "utf8");
  const initiativeMigration = await readFile("supabase/0027_initiative_structure.sql", "utf8");
  const raciMigration = await readFile("supabase/0028_initiative_raci.sql", "utf8");
  const docs = await readFile("docs/planning-hierarchy.md", "utf8");
  const skill = await readFile(".agents/skills/fmd-planning-structure/SKILL.md", "utf8");
  const initiativeSkill = await readFile(".agents/skills/fmd-initiative-planning/SKILL.md", "utf8");
  const initiativeRoute = await readFile("src/app/api/initiatives/route.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");
  const ui = await readFile("src/components/planning-app.tsx", "utf8");
  const display = await readFile("src/lib/display.ts", "utf8");
  const projectsOverview = await readFile("src/components/projects-overview.tsx", "utf8");
  const initiativeDialog = await readFile("src/components/initiative-dialog.tsx", "utf8");
  const pkg = await readFile("package.json", "utf8");

  assert.match(migration, /packages add column if not exists milestone_id/);
  assert.match(initiativeMigration, /owner_id/);
  assert.match(initiativeMigration, /success_criteria/);
  assert.match(initiativeMigration, /scope_constraints/);
  assert.match(raciMigration, /accountable_profile_id/);
  assert.match(raciMigration, /responsible_profile_ids/);
  assert.match(raciMigration, /consulted_profile_ids/);
  assert.match(raciMigration, /informed_profile_ids/);
  assert.match(docs, /Epic \/ Meilenstein[\s\S]*Initiative[\s\S]*Deliverable[\s\S]*Sub-Issue/);
  assert.match(docs, /Sprint ist ein Zeitcontainer/);
  assert.match(skill, /Sprint is a time container/);
  assert.match(initiativeSkill, /CEO or leadership outcome briefs/);
  assert.match(initiativeRoute, /requireOperationalLead/);
  assert.match(initiativeRoute, /Initiative-Owner ist erforderlich/);
  assert.match(initiativeRoute, /accountableProfileId/);
  assert.match(initiativeRoute, /responsibleProfileIds/);
  assert.match(github, /Epic \/ Milestone/);
  assert.match(github, /Initiative/);
  assert.match(github, /RACI Accountable/);
  assert.match(projectsOverview, /Epic \/ Meilenstein/);
  assert.match(projectsOverview, /Aktives Projekt/);
  assert.match(projectsOverview, /Erfolgskriterien/);
  assert.match(projectsOverview, /onEditInitiative/);
  assert.match(display, /initiativeMetaLabel/);
  assert.match(ui, /Initiative/);
  assert.match(ui, /InitiativeDialog/);
  assert.match(initiativeDialog, /Initiative-Brief/);
  assert.match(initiativeDialog, /Neue Initiative/);
  assert.match(initiativeDialog, /CustomDatePicker/);
  assert.match(initiativeDialog, /CustomSelect/);
  assert.match(ui, /expandedPackages/);
  assert.match(ui, /Alle einklappen/);
  assert.match(ui, /Alle ausklappen/);
  assert.match(ui, /aria-expanded=\{expanded\}/);
  assert.match(pkg, /verify:hierarchy/);
});

test("management repo cleanup plan protects legacy templates from deletion without approval", async () => {
  const plan = await readFile("docs/management-repo-v2-plan.md", "utf8");
  const deliverableTemplate = await readFile("docs/management-templates-v2/deliverable.yml", "utf8");
  const groupTemplate = await readFile("docs/management-templates-v2/initiative.yml", "utf8");
  const subIssueTemplate = await readFile("docs/management-templates-v2/sub-issue.yml", "utf8");

  assert.match(plan, /Keine Datei im Management-Repo löschen/);
  assert.match(plan, /Erst archivieren statt endgültig löschen/);
  assert.match(plan, /auto-triage\.yml/);
  assert.match(plan, /sprint-title-sync\.yml/);
  assert.match(deliverableTemplate, /GitHub ist Backup, nicht Quelle der Wahrheit/);
  assert.match(deliverableTemplate, /Acceptance Criteria/);
  assert.match(groupTemplate, /Epic \/ Meilenstein/);
  assert.match(subIssueTemplate, /nicht score-relevant/);
});
