import { readFile } from "node:fs/promises";
import { readFeatureSurface, readPlanningSurface } from "./helpers/planning-surface.mjs";
import test from "node:test";
import assert from "node:assert/strict";

test("platform migration contains the role, decision, score and sync contracts", async () => {
  const sql = await readFile("supabase/0002_founder_platform.sql", "utf8");

  assert.match(sql, /platform_role text/);
  assert.match(sql, /github_login text unique/);
  assert.match(sql, /decision_log/);
  assert.match(sql, /decision_confirmations/);
  assert.match(sql, /audit_log/);
  assert.match(sql, /review_status/);
  assert.match(sql, /github_sync_status/);
  assert.match(sql, /current_platform_role/);
});

test("github sync route keeps the app as source of truth", async () => {
  const route = await readFile("src/app/api/tasks/[id]/sync-github/route.ts", "utf8");
  const providerAuth = await readFile("src/lib/github-provider-auth.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");

  assert.match(route, /requireOperationalLead/);
  assert.match(route, /requireMatchingGitHubProviderToken/);
  assert.match(providerAuth, /x-github-provider-token/);
  assert.match(providerAuth, /githubUserForToken/);
  assert.match(providerAuth, /GitHub User-Token passt nicht zum angemeldeten Teamprofil/);
  assert.match(route, /buildSyncContext/);
  assert.match(route, /task_comments/);
  assert.match(route, /task_blockers/);
  assert.match(route, /task_activity/);
  assert.match(route, /parent_task_id/);
  assert.match(route, /createIfMissing/);
  assert.match(route, /Diese Aufgabe ist App-only/);
  assert.match(route, /Nur Deliverables werden als eigenständige GitHub-Issues gespiegelt/);
  assert.match(route, /github_sync_status: "pending"/);
  assert.match(route, /github_sync_status: "synced"/);
  assert.match(route, /github_sync_status: "failed"/);
  assert.match(github, /state: task\.status === "Erledigt" \? "closed" : "open"/);
});

test("operational leads can delete test tasks and close linked github issues", async () => {
  const taskRoute = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");
  const panelSidebar = await readFile("src/features/tasks/organisms/task-detail-panel-sidebar.tsx", "utf8");

  assert.match(taskRoute, /export async function DELETE/);
  assert.match(taskRoute, /Nur CEO oder Deputy können Aufgaben löschen/);
  assert.match(taskRoute, /archiveGitHubIssue/);
  assert.match(taskRoute, /githubClosed/);
  assert.match(github, /export async function archiveGitHubIssue/);
  assert.match(github, /state_reason: "not_planned"/);
  assert.match(github, /test\/deleted/);
  assert.match(panelSidebar, /Test & Bereinigung/);
  assert.match(panelSidebar, /Aufgabe löschen/);
});

test("github issue export includes structure review blockers and comments", async () => {
  const github = await readFile("src/lib/github.ts", "utf8");
  const ui = await readPlanningSurface();
  const panelSidebar = await readFile("src/features/tasks/organisms/task-detail-panel-sidebar.tsx", "utf8");
  const settingsOverviewUi = await readFile("src/features/settings/organisms/settings-overview.tsx", "utf8");
  const readinessUi = await readFile("src/features/settings/organisms/settings-readiness.tsx", "utf8");
  const platform = await readFile("src/lib/platform.ts", "utf8");

  assert.match(github, /taskIssueTitle/);
  assert.match(github, /taskIssueLabels/);
  assert.match(github, /task\.taskType === "deliverable" \? "deliverable"/);
  assert.match(github, /review:ready/);
  assert.match(github, /Problem Statement/);
  assert.match(github, /Intended Outcome/);
  assert.match(github, /Acceptance Criteria/);
  assert.match(github, /Score-relevant/);
  assert.match(github, /Offene Blocker/);
  assert.match(github, /Relationships/);
  assert.match(github, /Wartet auf/);
  assert.match(github, /Blockiert/);
  assert.match(github, /Letzte Kommentare/);
  assert.match(github, /Aktivitätsprotokoll/);
  assert.match(github, /Parent Deliverable/);
  assert.match(github, /Source of Truth/);
  assert.match(github, /linkedIssueNumber/);
  assert.match(github, /task\.issueNumber/);
  assert.match(platform, /hasGitHubIssue/);
  assert.match(ui, /syncTaskToGitHub/);
  assert.match(panelSidebar, /Jetzt spiegeln/);
  assert.match(ui, /SettingsOverview/);
  assert.match(settingsOverviewUi, /GitHubSyncQueueSection/);
  assert.match(readinessUi, /GitHub Sync Queue/);
  assert.match(readinessUi, /Verknüpfte Issues synchronisieren/);
  assert.match(ui, /createIfMissing: false/);
});

test("task relationships use github-like blocked by and blocking semantics", async () => {
  const migration = await readFile("supabase/0016_task_relationship_edges.sql", "utf8");
  const route = await readFile("src/app/api/tasks/[id]/relationships/route.ts", "utf8");
  const data = await readFile("src/lib/planning-data.ts", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");
  const platform = await readFile("src/lib/platform.ts", "utf8");
  const display = await readFile("src/lib/display.ts", "utf8");
  const panel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  const relationshipUi = await readFile("src/features/tasks/molecules/relationship-list.tsx", "utf8");
  const detail = await readFile("src/features/tasks/templates/task-detail-page.tsx", "utf8");
  const taskDetailWorkflow = await readFile("src/features/tasks/hooks/use-task-detail-workflow.ts", "utf8");
  const relationshipHook = await readFile("src/features/tasks/hooks/use-task-relationships.ts", "utf8");
  const relationshipSection = await readFile("src/features/tasks/organisms/task-relationships-section.tsx", "utf8");
  const taskApiClient = await readFile("src/features/tasks/model/task-api-client.ts", "utf8");
  const relationshipViewModel = await readFile("src/lib/relationship-view-model.ts", "utf8");
  const script = await readFile("scripts/migrate-task-relationships.mjs", "utf8");

  assert.match(migration, /create table if not exists task_relationship_edges/);
  assert.match(migration, /blocked_by/);
  assert.match(migration, /blocks/);
  assert.match(migration, /relates_to/);
  assert.match(route, /requireOperationalLead/);
  assert.match(route, /task.relationship_created/);
  assert.match(route, /task.relationship_deleted/);
  assert.match(route, /github_sync_status: "not_synced"/);
  assert.match(types, /TaskRelationType/);
  assert.match(data, /task_relationship_edges/);
  assert.match(platform, /taskRelationsFor/);
  assert.match(platform, /hasOpenWaitingRelation/);
  assert.match(platform, /blockingTask && blockingTask\.status !== "Erledigt"/);
  assert.match(display, /Diese Aufgabe kann erst sauber weitergehen/);
  assert.match(display, /Verknüpft mit/);
  assert.match(relationshipViewModel, /relationshipBadgeFor/);
  assert.match(relationshipViewModel, /Blockiert aktuell/);
  assert.match(relationshipViewModel, /Blocker erledigt/);
  assert.match(relationshipViewModel, /Blockiert andere/);
  assert.match(relationshipViewModel, /Abhängigkeit erfüllt/);
  assert.match(relationshipViewModel, /Verknüpft/);
  assert.match(relationshipViewModel, /relationMatchesDraft/);
  const panelDependencies = await readFile("src/features/tasks/molecules/task-detail-panel-dependencies-section.tsx", "utf8");
  assert.match(panelDependencies, /Relationship hinzufügen/);
  assert.match(panelDependencies, /Relationship existiert bereits/);
  assert.match(panelDependencies, /Diese Relationship ist bereits gespeichert/);
  assert.match(panelDependencies, /relationMatchesDraft/);
  assert.match(detail, /useTaskDetailWorkflow/);
  assert.match(taskDetailWorkflow, /useTaskRelationships/);
  assert.match(detail, /task=\{task\}/);
  assert.match(relationshipHook, /Relationship konnte nicht gespeichert werden/);
  assert.match(relationshipHook, /Relationship konnte nicht entfernt werden/);
  assert.match(taskApiClient, /api\/tasks\/\$\{taskId\}\/relationships/);
  assert.match(taskApiClient, /method: "POST"/);
  assert.match(taskApiClient, /method: "DELETE"/);
  assert.match(relationshipHook, /setRelations\(\(current\) => \[localRelation, \.\.\.current\]\)/);
  assert.match(panel, /TaskDetailPanelDependenciesSection/);
  assert.match(panelDependencies, /RelationshipList/);
  assert.match(panelDependencies, /Wartet auf/);
  assert.match(relationshipUi, /relationshipHelpText/);
  assert.match(detail, /TaskRelationshipsSection/);
  assert.match(relationshipSection, /RelationshipPanelList/);
  assert.match(relationshipSection, /Relationship hinzufügen/);
  assert.match(relationshipSection, /relationshipBadgeFor/);
  assert.match(relationshipSection, /relationshipBadgeToneClass/);
  assert.match(relationshipSection, /Relationship existiert bereits/);
  assert.match(relationshipSection, /relationshipHelpText/);
  assert.match(script, /task_dependencies/);
  assert.match(script, /relation_type: "blocked_by"/);
});

test("github sync queue is reopened by task comments blockers and relationship changes", async () => {
  const taskRoute = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const commentsRoute = await readFile("src/app/api/tasks/[id]/comments/route.ts", "utf8");
  const blockersRoute = await readFile("src/app/api/tasks/[id]/blockers/route.ts", "utf8");
  const relationshipsRoute = await readFile("src/app/api/tasks/[id]/relationships/route.ts", "utf8");
  const syncRoute = await readFile("src/app/api/tasks/[id]/sync-github/route.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");

  assert.match(taskRoute, /payload\.githubSyncStatus === undefined/);
  assert.match(taskRoute, /github_sync_status = "not_synced"/);
  assert.match(commentsRoute, /github_sync_status: githubSyncError \? "failed" : "not_synced"/);
  assert.match(commentsRoute, /github_sync_error: githubSyncError \|\| null/);
  assert.match(blockersRoute, /github_sync_status: "not_synced"/);
  assert.match(relationshipsRoute, /github_sync_status: "not_synced"/);
  assert.match(syncRoute, /task_relationship_edges/);
  assert.match(syncRoute, /activitiesResult/);
  assert.match(syncRoute, /profileNameById\.get\(relation\.task\?\.owner/);
  assert.match(github, /Problem Statement/);
  assert.match(github, /Review fällig bis/);
  assert.match(github, /Priorität/);
  assert.match(github, /Verknüpft mit/);
});

test("github sync verification is read-only and checks the management repo", async () => {
  const script = await readFile("scripts/verify-github-sync.mjs", "utf8");
  const pkg = await readFile("package.json", "utf8");

  assert.match(pkg, /verify:github-sync/);
  assert.match(script, /logged_in_github_user_provider_token/);
  assert.match(script, /GITHUB_SYNC_OWNER/);
  assert.match(script, /GITHUB_SYNC_REPO/);
  assert.match(script, /linkedDeliverables\.filter/);
  assert.match(script, /automaticSyncScope/);
  assert.match(script, /syncQueuePreview/);
  assert.match(script, /appOnlyPreview/);
  assert.doesNotMatch(script, /method: "POST"/);
  assert.doesNotMatch(script, /method: "PATCH"/);
  assert.doesNotMatch(script, /method: "DELETE"/);
});

test("app-only tasks are visibly marked without creating github issues", async () => {
  const ui = await readPlanningSurface();
  const panel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  const panelSidebar = await readFile("src/features/tasks/organisms/task-detail-panel-sidebar.tsx", "utf8");
  const readinessUi = await readFile("src/features/settings/organisms/settings-readiness.tsx", "utf8");
  const taskCard = await readFile("src/features/tasks/molecules/task-card.tsx", "utf8");
  const detail = await readFile("src/features/tasks/templates/task-detail-page.tsx", "utf8");
  const detailGitHubSyncCard = await readFile("src/features/tasks/molecules/task-github-sync-card.tsx", "utf8");

  assert.match(ui, /GitHubMissingBadge/);
  assert.match(taskCard, /App-only/);
  assert.match(readinessUi, /App-only-Aufgaben bleiben dauerhaft sichtbar/);
  assert.match(readinessUi, /Diese Liste bleibt dauerhaft erhalten/);
  assert.match(readinessUi, /task\.taskType === "deliverable"/);
  assert.doesNotMatch(readinessUi, /task\.taskType === "deliverable" \|\| task\.taskType === "proposal"/);
  assert.match(readinessUi, /Deliverables bleiben App-only/);
  assert.match(readinessUi, /GitHub anlegen/);
  assert.match(readinessUi, /Keine App-only Aufgaben ohne GitHub-Issue/);
  assert.match(taskCard, /Nur in der App: noch kein GitHub-Issue verknüpft/);
  assert.match(panel, /TaskDetailPanelSidebar/);
  assert.match(panelSidebar, /GitHub-Issue anlegen/);
  assert.match(ui, /createIfMissing: true/);
  assert.match(ui, /onCreateGitHubIssue/);
  assert.match(detailGitHubSyncCard, /Nur in der App: noch kein GitHub-Issue verknüpft/);
  assert.match(detailGitHubSyncCard, /GitHub-Issue anlegen/);
  assert.match(detail, /createIfMissing: true/);
  assert.match(detail, /githubState/);
  assert.match(panelSidebar, /nicht automatisch dupliziert/);
  assert.match(detailGitHubSyncCard, /nicht automatisch dupliziert/);
});

test("existing management issues are linked before creating duplicates", async () => {
  const script = await readFile("scripts/plan-github-issue-linking.mjs", "utf8");
  const docs = await readFile("docs/planning-hierarchy.md", "utf8");

  assert.match(script, /normalizeTitle/);
  assert.match(script, /exactMatches/);
  assert.match(script, /ambiguousMatches/);
  assert.match(script, /github_issue_number/);
  assert.match(script, /--apply/);
  assert.match(docs, /Bestehende GitHub-Issues/);
  assert.match(docs, /nicht gelöscht und nicht dupliziert/);
});

test("legacy github body sections are not kept inside evidence link fields", async () => {
  const repairScript = await readFile("scripts/repair-evidence-link-sections.mjs", "utf8");
  const githubCommentsRoute = await readFile("src/app/api/tasks/[id]/github-comments/route.ts", "utf8");

  assert.match(repairScript, /cleanEvidenceLinkValue/);
  assert.match(repairScript, /Non-Tech Summary/);
  assert.match(repairScript, /Follow-up Issues/);
  assert.match(repairScript, /No response/);
  assert.match(repairScript, /evidence_link/);
  assert.match(repairScript, /--apply/);
  assert.match(repairScript, /github_sync_status = "not_synced"|github_sync_status: "not_synced"/);
  assert.match(githubCommentsRoute, /extractEvidenceFromIssueBody/);
});

test("github oauth prepares user-based sync without storing provider tokens", async () => {
  const ui = await readPlanningSurface();
  const requestContext = await readFile("src/features/planning/hooks/use-planning-request-context.ts", "utf8");
  const browserApiClient = await readFile("src/lib/browser-api-client.ts", "utf8");
  const authHook = await readFile("src/features/planning/hooks/use-planning-auth.ts", "utf8");
  const readinessUi = await readFile("src/features/settings/organisms/settings-readiness.tsx", "utf8");
  const detail = await readFile("src/features/tasks/templates/task-detail-page.tsx", "utf8");
  const taskDetailWorkflow = await readFile("src/features/tasks/hooks/use-task-detail-workflow.ts", "utf8");
  const detailGitHubSyncCard = await readFile("src/features/tasks/molecules/task-github-sync-card.tsx", "utf8");
  const githubStatus = await readFile("src/features/planning/molecules/github-connection-status.tsx", "utf8");
  const planningHeader = await readFile("src/features/planning/organisms/planning-header.tsx", "utf8");
  const thread = await readFile("src/features/tasks/organisms/task-comment-thread.tsx", "utf8");
  const commentHook = await readFile("src/features/tasks/hooks/use-task-comments.ts", "utf8");
  const taskApiClient = await readFile("src/features/tasks/model/task-api-client.ts", "utf8");
  const commentBody = await readFile("src/features/tasks/atoms/task-comment-body.tsx", "utf8");
  const commentComposer = await readFile("src/features/tasks/molecules/task-comment-composer.tsx", "utf8");
  const githubCommentImage = await readFile("src/features/tasks/molecules/github-comment-image.tsx", "utf8");
  const providerTokenMemory = await readFile("src/lib/github-provider-token.ts", "utf8");
  const providerAuth = await readFile("src/lib/github-provider-auth.ts", "utf8");
  const supabase = await readFile("src/lib/supabase.ts", "utf8");
  const serverSupabase = await readFile("src/lib/supabase-server.ts", "utf8");
  const proxy = await readFile("src/proxy.ts", "utf8");
  const callback = await readFile("src/app/auth/callback/route.ts", "utf8");
  const syncRoute = await readFile("src/app/api/tasks/[id]/sync-github/route.ts", "utf8");
  const commentsRoute = await readFile("src/app/api/tasks/[id]/comments/route.ts", "utf8");
  const attachmentRoute = await readFile("src/app/api/tasks/[id]/attachments/route.ts", "utf8");
  const github = await readFile("src/lib/github.ts", "utf8");
  const authDocs = await readFile("docs/auth-flow.md", "utf8");
  const rules = await readFile("AGENTS.md", "utf8");

  assert.match(ui, /usePlanningAuth/);
  assert.match(authHook, /signInWithOAuth/);
  assert.match(authHook, /scopes: "repo read:user user:email"/);
  assert.match(authHook, /provider_token/);
  assert.match(requestContext, /createBrowserApiClient/);
  assert.match(browserApiClient, /x-github-provider-token/);
  assert.match(browserApiClient, /getRememberedGitHubProviderToken/);
  assert.match(browserApiClient, /rememberGitHubProviderToken/);
  assert.doesNotMatch(detail, /x-github-provider-token|getRememberedGitHubProviderToken|getBrowserSupabase|auth\.getSession/);
  assert.match(supabase, /createBrowserClient/);
  assert.match(supabase, /browserSupabaseUrl && browserSupabaseAnonKey/);
  assert.match(supabase, /persistSession: true/);
  assert.match(supabase, /autoRefreshToken: true/);
  assert.match(serverSupabase, /createServerClient/);
  assert.match(proxy, /supabase\.auth\.getUser\(\)/);
  assert.match(callback, /exchangeCodeForSession\(code\)/);
  assert.match(authHook, /refreshSessionState/);
  assert.match(authHook, /supabase\.auth\.refreshSession\(\)/);
  assert.match(authHook, /visibilitychange/);
  assert.match(authHook, /5 \* 60 \* 1000/);
  assert.match(authHook, /markGitHubReauthAttempt/);
  assert.match(authHook, /sessionStorage/);
  assert.doesNotMatch(planningHeader, /markGitHubReauthAttempt/);
  assert.doesNotMatch(planningHeader, /hasGitHubReauthAttempt/);
  assert.match(authHook, /clearRememberedGitHubProviderToken/);
  assert.match(detail, /useTaskDetailWorkflow/);
  assert.match(taskDetailWorkflow, /createBrowserApiClient/);
  assert.match(ui, /GitHubConnectionStatus/);
  assert.match(detail, /GitHubConnectionStatus/);
  assert.match(githubStatus, /GitHub-Verbindung erneuern/);
  assert.match(githubStatus, /GitHub-Sync, Kommentare und Anhänge/);
  assert.doesNotMatch(readinessUi, /GitHub-Verbindung .*erneuern/);
  assert.doesNotMatch(readinessUi, /zentrale Verbindung im Header/);
  assert.doesNotMatch(detailGitHubSyncCard, /GitHub-Verbindung .*erneuern/);
  assert.doesNotMatch(detailGitHubSyncCard, /frische Autorisierung/);
  assert.match(commentBody, /GitHubCommentImage/);
  assert.match(thread, /TaskCommentComposer/);
  assert.match(taskDetailWorkflow, /useTaskComments/);
  assert.match(commentHook, /createTaskCommentRequest/);
  assert.doesNotMatch(commentHook, /x-github-provider-token|getRememberedGitHubProviderToken|getBrowserSupabase|auth\.getSession/);
  assert.match(commentComposer, /onUploadAttachment/);
  assert.match(githubCommentImage, /loadGitHubAssetBlob/);
  assert.doesNotMatch(githubCommentImage, /getBrowserSupabase|getRememberedGitHubProviderToken|auth\.getSession/);
  assert.match(taskApiClient, /includeGitHubToken: true/);
  assert.match(providerTokenMemory, /rememberedGitHubProviderToken/);
  assert.match(providerTokenMemory, /clearRememberedGitHubProviderToken/);
  assert.doesNotMatch(providerTokenMemory, /localStorage|sessionStorage|indexedDB/i);
  assert.doesNotMatch(readinessUi, /onReconnectGitHub/);
  assert.doesNotMatch(detailGitHubSyncCard, /onReconnectGitHub/);
  assert.match(readinessUi, /GitHub User-Token/);
  assert.match(syncRoute, /requireMatchingGitHubProviderToken/);
  assert.match(providerAuth, /githubUser\.login\.toLowerCase\(\) !== expectedLogin/);
  assert.match(commentsRoute, /createGitHubIssueComment/);
  assert.match(commentsRoute, /githubSyncError/);
  assert.match(attachmentRoute, /requireMatchingGitHubProviderToken/);
  assert.match(providerAuth, /GitHub User-Token passt nicht zum angemeldeten Teamprofil/);
  assert.match(providerAuth, /x-github-provider-token/);
  assert.doesNotMatch(commentsRoute, /task_comments"\)\.delete/);
  assert.match(github, /createGitHubIssueComment/);
  assert.match(github, /uploadGitHubAttachment/);
  assert.match(github, /getGitHubIssue/);
  assert.match(github, /api\.github\.com\/repos\/\$\{owner\}\/\$\{repo\}\/contents/);
  assert.match(github, /https:\/\/api\.github\.com\/user/);
  assert.match(rules, /provider_token/);
  assert.match(rules, /Never persist or log provider tokens/);
  assert.match(authDocs, /```mermaid/);
  assert.match(authDocs, /Production Boot/);
  assert.match(authDocs, /GitHub Provider Token Reconnect/);
  assert.match(authDocs, /must not start OAuth only because a task was opened/);
  assert.match(authDocs, /must not store Supabase tokens, refresh tokens, GitHub provider tokens/);
  assert.doesNotMatch(syncRoute, /GITHUB_SYNC_TOKEN/);
  assert.doesNotMatch(commentsRoute, /GITHUB_SYNC_TOKEN/);
});

test("comments blockers and notification outbox are modeled before Google Chat delivery", async () => {
  const migration = await readFile("supabase/0005_comments_blockers_notifications.sql", "utf8");
  const externalMigration = await readFile("supabase/0018_task_external_comments.sql", "utf8");
  const data = await readFile("src/lib/planning-data.ts", "utf8");
  const commentsRoute = await readFile("src/app/api/tasks/[id]/comments/route.ts", "utf8");
  const githubCommentsRoute = await readFile("src/app/api/tasks/[id]/github-comments/route.ts", "utf8");
  const githubAssetsRoute = await readFile("src/app/api/github-assets/route.ts", "utf8");
  const attachmentRoute = await readFile("src/app/api/tasks/[id]/attachments/route.ts", "utf8");
  const providerAuth = await readFile("src/lib/github-provider-auth.ts", "utf8");
  const blockersRoute = await readFile("src/app/api/tasks/[id]/blockers/route.ts", "utf8");
  const taskRoute = await readFile("src/app/api/tasks/[id]/route.ts", "utf8");
  const syncRoute = await readFile("src/app/api/tasks/[id]/sync-github/route.ts", "utf8");
  const ui = await readPlanningSurface();
  const sprintUi = await readFeatureSurface("src/features/sprint");
  const panel = await readFile("src/features/tasks/organisms/task-detail-panel.tsx", "utf8");
  const panelBlockerSection = await readFile("src/features/tasks/molecules/task-detail-panel-blocker-section.tsx", "utf8");
  const thread = await readFile("src/features/tasks/organisms/task-comment-thread.tsx", "utf8");
  const commentHook = await readFile("src/features/tasks/hooks/use-task-comments.ts", "utf8");
  const taskApiClient = await readFile("src/features/tasks/model/task-api-client.ts", "utf8");
  const commentBody = await readFile("src/features/tasks/atoms/task-comment-body.tsx", "utf8");
  const commentComposer = await readFile("src/features/tasks/molecules/task-comment-composer.tsx", "utf8");
  const commentTimeline = await readFile("src/features/tasks/molecules/task-comment-timeline.tsx", "utf8");
  const githubCommentImage = await readFile("src/features/tasks/molecules/github-comment-image.tsx", "utf8");
  const mentions = await readFile("src/lib/mentions.ts", "utf8");
  const notificationPolicy = await readFile("src/lib/notification-policy.ts", "utf8");
  const googleChat = await readFile("src/lib/google-chat.ts", "utf8");
  const types = await readFile("src/lib/types.ts", "utf8");

  assert.match(migration, /create table if not exists task_comments/);
  assert.match(externalMigration, /create table if not exists task_external_comments/);
  assert.match(externalMigration, /unique \(source, external_id\)/);
  assert.match(migration, /create table if not exists task_blockers/);
  assert.match(migration, /create table if not exists notification_events/);
  assert.match(migration, /review_due_at/);
  assert.match(data, /taskComments/);
  assert.match(data, /taskExternalComments/);
  assert.match(data, /task_external_comments/);
  assert.match(data, /taskBlockers/);
  assert.match(data, /taskActivity/);
  assert.match(data, /task_activity/);
  assert.match(data, /notificationEvents/);
  assert.match(commentsRoute, /task.comment/);
  assert.match(commentsRoute, /mentionedProfileIds/);
  assert.match(commentsRoute, /task.mention/);
  assert.match(commentsRoute, /Du wurdest erwähnt/);
  assert.match(commentsRoute, /Kommentar hinzugefügt/);
  assert.match(mentions, /githubLogin/);
  assert.match(notificationPolicy, /task\.mention/);
  assert.match(notificationPolicy, /Erwähnung/);
  assert.match(googleChat, /eventUrl/);
  assert.match(googleChat, /\/tasks\/\$\{encodeURIComponent\(event\.entityId\)\}/);
  assert.match(googleChat, /Aufgabe öffnen/);
  assert.match(attachmentRoute, /requireFounder/);
  assert.match(attachmentRoute, /uploadGitHubAttachment/);
  assert.match(attachmentRoute, /\.fmd-attachments\/tasks/);
  assert.match(attachmentRoute, /10 MB/);
  assert.match(attachmentRoute, /markdown/);
  assert.match(githubCommentsRoute, /listGitHubIssueComments/);
  assert.match(githubCommentsRoute, /getGitHubIssue/);
  assert.match(githubCommentsRoute, /extractEvidenceFromIssueBody/);
  assert.match(githubCommentsRoute, /Evidence aus GitHub-Issue importiert/);
  assert.match(githubCommentsRoute, /evidenceLink/);
  assert.match(githubCommentsRoute, /isAppMirroredComment/);
  assert.match(githubCommentsRoute, /task_external_comments/);
  assert.match(githubCommentsRoute, /source,external_id/);
  assert.doesNotMatch(githubCommentsRoute, /events/);
  assert.match(blockersRoute, /task.blocker_reported/);
  assert.match(taskRoute, /Status geändert/);
  assert.match(taskRoute, /activityMessages/);
  assert.match(syncRoute, /GitHub Sync ausgeführt/);
  assert.match(panel, /TaskDetailPanelBlockerSection/);
  assert.match(panelBlockerSection, /Blocker melden/);
  assert.match(panel, /TaskCommentThread/);
  assert.match(ui, /selectedTaskActivity/);
  assert.match(commentHook, /useTaskComments/);
  assert.match(taskApiClient, /api\/tasks\/\$\{taskId\}\/comments/);
  assert.match(taskApiClient, /api\/tasks\/\$\{taskId\}\/attachments/);
  assert.match(taskApiClient, /api\/tasks\/\$\{taskId\}\/github-comments/);
  assert.match(commentComposer, /mentionOptions/);
  assert.match(commentComposer, /insertMention/);
  assert.match(commentHook, /Kommentar konnte nicht gespeichert werden/);
  assert.match(commentHook, /Anhang konnte nicht hochgeladen werden/);
  assert.match(commentHook, /GitHub-Kommentare konnten nicht aktualisiert werden/);
  assert.match(commentHook, /autoImportedGitHubCommentsRef/);
  assert.match(thread, /Kommunikation/);
  assert.match(thread, /activities/);
  assert.match(thread, /externalComments/);
  assert.match(thread, /GitHub aktualisieren/);
  assert.match(thread, /github-comment/);
  assert.match(thread, /timeline/);
  assert.match(thread, /TaskCommentTimeline/);
  assert.match(commentTimeline, /describeActivity/);
  assert.match(commentTimeline, /repairGermanText/);
  assert.match(commentTimeline, /activityToneClass/);
  assert.match(commentTimeline, /Status geändert/);
  assert.match(commentTimeline, /Review finalisiert/);
  assert.match(commentTimeline, /Relationship/);
  assert.match(thread, /CommentBody/);
  assert.match(thread, /TaskCommentComposer/);
  assert.match(githubCommentImage, /<img\b/);
  assert.match(commentBody, /react-markdown/);
  assert.match(commentBody, /remark-gfm/);
  assert.match(commentBody, /remark-breaks/);
  assert.match(commentBody, /GitHubCommentImage/);
  assert.match(commentBody, /overflow-x-auto/);
  assert.match(commentBody, /\[overflow-wrap:anywhere\]/);
  assert.match(commentBody, /skipHtml/);
  assert.match(githubCommentImage, /loadGitHubAssetBlob/);
  assert.match(taskApiClient, /\/api\/github-assets\?url=/);
  assert.match(githubCommentImage, /URL\.createObjectURL/);
  assert.match(commentBody, /safeHref/);
  assert.match(githubCommentImage, /useState\(false\)/);
  assert.match(githubCommentImage, /loadViaProxy/);
  assert.match(githubCommentImage, /if \(!isGitHubAsset \|\| proxyAttempted\)/);
  assert.match(commentComposer, /showCommentPreview/);
  assert.match(commentComposer, /Vorschau/);
  assert.match(commentComposer, /renderPreview/);
  assert.match(githubCommentImage, /loadGitHubAssetBlob/);
  assert.match(commentComposer, /onUploadAttachment/);
  assert.match(commentComposer, /type="file"/);
  assert.match(commentComposer, /Paperclip/);
  assert.match(commentComposer, /Anhang/);
  assert.match(githubAssetsRoute, /requireFounder/);
  assert.match(githubAssetsRoute, /requireMatchingGitHubProviderToken/);
  assert.match(providerAuth, /x-github-provider-token/);
  assert.match(providerAuth, /githubUserForToken/);
  assert.match(githubAssetsRoute, /user-attachments\/assets/);
  assert.match(githubAssetsRoute, /content-type/);
  assert.match(githubAssetsRoute, /image\//);
  assert.match(githubCommentImage, /Anhang in GitHub öffnen/);
  assert.match(thread, /new Date\(left\.createdAt\)/);
  assert.match(commentTimeline, /Nachfragen/);
  assert.match(commentComposer, /Kommentieren/);
  assert.match(types, /TaskActivity/);
  assert.match(types, /TaskExternalComment/);
  assert.match(sprintUi, /Review bis/);
});
