import type { Task } from "@/lib/types";

export function taskDetailStoryTask(overrides: Partial<Task> = {}): Task {
  return {
    id: "task-1",
    order: 0,
    title: "Task",
    description: "",
    status: "Offen",
    priority: "P2",
    assignee: "",
    owner: "",
    workstream: "",
    fixedDate: "",
    definitionOfDone: "",
    dependsOn: "",
    evidenceLink: "",
    evidenceLinks: [],
    linkedPullRequests: [],
    issueNumber: "",
    issueUrl: "",
    note: "",
    watched: false,
    hours: 0,
    sprintId: "",
    reviewStatus: "not_requested",
    scorePoints: 0,
    scoreFinal: false,
    githubRepo: "management",
    githubIssueNumber: null,
    githubIssueUrl: "",
    githubIssueSyncStatus: "not_synced",
    githubIssueLastSyncedAt: "",
    githubIssueSyncError: "",
    taskType: "deliverable",
    parentTaskId: "",
    approvalStatus: "approved",
    approvalRevision: 1,
    parentApprovalStatus: "approved",
    scoreRelevant: true,
    ...overrides,
  };
}
