"use client";

import { useRef } from "react";
import { usePlanningBootstrapState, type PlanningBootstrapStateOptions } from "@/features/planning/hooks/use-planning-bootstrap-state";
import { usePlanningCommandRegistry } from "@/features/planning/hooks/use-planning-command-registry";
import { usePlanningDerivedState } from "@/features/planning/hooks/use-planning-derived-state";
import { usePlanningTaskSelection } from "@/features/planning/hooks/use-planning-task-selection";
import { useTaskDetailDataLoader } from "@/features/tasks/hooks/use-task-detail-data-loader";

type PlanningAppControllerOptions = PlanningBootstrapStateOptions;

export function usePlanningAppController({
  initialData,
  initialHeaderData,
  initialWorkspace,
  source,
  authRequired,
  initialAuthUser = null,
  initialCurrentProfile = null,
  initialProtectedDataLoaded = false,
  initialAuthError = "",
}: PlanningAppControllerOptions) {
  const sidebarRef = useRef<HTMLElement | null>(null);
  const bootstrap = usePlanningBootstrapState({
    initialData,
    initialHeaderData,
    initialWorkspace,
    source,
    authRequired,
    initialAuthUser,
    initialCurrentProfile,
    initialProtectedDataLoaded,
    initialAuthError,
  });
  const {
    actualProfile,
    apiClient,
    applyPlanningShellStateUpdate,
    authAvailable,
    authBusy,
    authChecked,
    authError,
    authNotice,
    authUser,
    canChangeTaskStatus,
    canManageFinalTaskStatus,
    canManageTaskMeta,
    currentProfile,
    currentProfileId,
    data,
    devProfileId,
    devRoleSwitchAvailable,
    filters,
    focusModeActive,
    hasPlanningBoardUrlState,
    hasPlanningFilterUrlState,
    githubConnectionState,
    githubInstallationAvailable,
    githubUserConnected,
    waitingGitHubCommentCount,
    githubReauthFailed,
    githubSyncQueueOpen,
    headerData,
    isPending,
    initiativeDialogDefaults,
    epicDeleteTarget,
    epicDialogDefaults,
    mobileNavOpen,
    planningLevel,
    planningParentFilterId,
    planningRemoteChangesAvailable,
    planningRemoteChangesRefreshing,
    protectedDataLoaded,
    refreshCurrentWorkspaceModel,
    refreshCurrentWorkspaceModelWithResult,
    refreshPlanningRemoteChanges,
    saveError,
    selectedTaskId,
    setData,
    setDevProfileId,
    setFilters,
    setGithubSyncQueueOpen,
    setHeaderData,
    setInitiativeDialogDefaults,
    setEpicDeleteTarget,
    setEpicDialogDefaults,
    setMobileNavOpen,
    setPlanningLevel,
    setPlanningParentFilterId,
    setSaveError,
    setSelectedTaskId,
    setShowFilters,
    setShowNotifications,
    setSprintPlanningOptions,
    setStatusGuardNotice,
    setStatusGuardTaskId,
    setTaskDialogDefaults,
    setView,
    setWorkspace,
    showFilters,
    showNotifications,
    signIn,
    signOut,
    sprintPlanningOptions,
    startTransition,
    statusGuardNotice,
    statusGuardTaskId,
    taskDialogDefaults,
    toggleFocusMode,
    view,
    workspace,
  } = bootstrap;

  const commandContext = {
    apiClient,
    applyPlanningShellStateUpdate,
    canChangeTaskStatus,
    canManageFinalTaskStatus,
    canManageTaskMeta,
    currentProfile,
    data,
    githubInstallationAvailable,
    githubUserConnected,
    setData,
    setSaveError,
    source,
    startTransition,
  };

  const taskSelection = usePlanningTaskSelection({
    data,
    selectedTaskId,
    setSelectedTaskId,
  });
  const {
    backTaskPanel,
    closeTaskPanel,
    openTaskPanel,
    selectedTask,
  } = taskSelection;
  const taskDetailDataLoader = useTaskDetailDataLoader({
    apiClient,
    applyPlanningShellStateUpdate,
    selectedTask,
    source,
    startTransition,
  });

  const derivedState = usePlanningDerivedState({
    currentProfile,
    data,
    filters,
    planningLevel,
    setInitiativeDialogDefaults,
    setEpicDialogDefaults,
    setTaskDialogDefaults,
    statusGuardTaskId,
    view,
    workspace,
  });
  const commandRegistry = usePlanningCommandRegistry({
    closeTaskPanel,
    commandContext,
    currentProfileId,
    data,
    hasPlanningBoardUrlState,
    hasPlanningFilterUrlState,
    openTaskPanel,
    refreshCurrentWorkspaceModel,
    refreshCurrentWorkspaceModelWithResult,
    selectedTask,
    setFilters,
    setHeaderData,
    setInitiativeDialogDefaults,
    setEpicDeleteTarget,
    setEpicDialogDefaults,
    setShowNotifications,
    setStatusGuardNotice,
    setStatusGuardTaskId,
    setTaskDialogDefaults,
    setView,
    setWorkspace,
    sprintPlanningOptions,
    workspace,
  });
  const { boardState } = commandRegistry;

  const releaseSidebarFocus = () => {
    const activeElement = document.activeElement;
    if (activeElement instanceof HTMLElement && sidebarRef.current?.contains(activeElement)) {
      activeElement.blur();
    }
  };

  return {
    actualProfile,
    authAvailable,
    authBusy,
    authChecked,
    authError,
    authNotice,
    authUser,
    canChangeTaskStatus,
    canManageFinalTaskStatus,
    canManageTaskMeta,
    backTaskPanel,
    closeTaskPanel,
    currentProfile,
    data,
    devProfileId,
    devRoleSwitchAvailable,
    filters,
    filtersAvailable: derivedState.filtersAvailable,
    focusModeActive,
    githubConnectionState,
    githubInstallationAvailable,
    githubUserConnected,
    waitingGitHubCommentCount,
    githubReauthFailed,
    githubSyncQueueOpen,
    headerData,
    headerActions: derivedState.headerActions,
    initiativeDialogDefaults,
    epicDeleteTarget,
    epicDialogDefaults,
    isPending,
    metrics: derivedState.metrics,
    mobileNavOpen,
    planningLevel,
    planningParentFilterId,
    planningRemoteChangesAvailable,
    planningRemoteChangesRefreshing,
    openTaskPanel,
    protectedDataLoaded,
    refreshCurrentWorkspaceModel,
    refreshPlanningRemoteChanges,
    releaseSidebarFocus,
    apiClient,
    saveError,
    selectedInitiative: taskSelection.selectedInitiative,
    selectedTask,
    selectedTaskId,
    selectedTaskActivity: taskSelection.selectedTaskActivity,
    selectedTaskBlockers: taskSelection.selectedTaskBlockers,
    selectedTaskComments: taskSelection.selectedTaskComments,
    selectedTaskDetailError: taskDetailDataLoader.selectedTaskDetailError,
    selectedTaskDetailLoading: taskDetailDataLoader.selectedTaskDetailLoading,
    selectedTaskExternalComments: taskSelection.selectedTaskExternalComments,
    selectedTaskSubIssues: taskSelection.selectedTaskSubIssues,
    taskPanelPreviousTask: taskSelection.taskPanelPreviousTask,
    setData,
    setDevProfileId,
    setFilters,
    setGithubSyncQueueOpen,
    setInitiativeDialogDefaults,
    setEpicDeleteTarget,
    setEpicDialogDefaults,
    setMobileNavOpen,
    setPlanningLevel,
    setPlanningParentFilterId,
    setShowFilters,
    setShowNotifications,
    setSprintPlanningOptions,
    setStatusGuardNotice,
    setStatusGuardTaskId,
    setTaskDialogDefaults,
    setView,
    showFilters,
    showNotifications,
    sidebarRef,
    signIn,
    signOut,
    sprintPlanningOptions,
    source,
    statusGuardNotice,
    statusGuardTask: derivedState.statusGuardTask,
    taskDialogDefaults,
    toggleFocusMode,
    view,
    visibleTasks: derivedState.visibleTasks,
    workspace,
    setWorkspace,
    ...boardState,
    ...commandRegistry.eventCommands,
    ...commandRegistry.fmdToolCommands,
    ...commandRegistry.founderOpsSettingsCommands,
    ...commandRegistry.initiativeCommands,
    ...commandRegistry.epicCommands,
    ...commandRegistry.notificationCommands,
    ...commandRegistry.ownProfileSettingsCommands,
    ...commandRegistry.profileSettingsCommands,
    ...commandRegistry.reviewCommands,
    ...commandRegistry.sprintCommands,
    ...commandRegistry.weeklyAttendanceCommands,
    ...commandRegistry.taskCollaborationCommands,
    ...commandRegistry.taskMutationCommands,
  };
}

export type PlanningAppController = ReturnType<typeof usePlanningAppController>;
