"use client";

import { useRouter } from "next/navigation";
import { useRef } from "react";
import { usePlanningBootstrapState, type PlanningBootstrapStateOptions } from "@/features/planning/hooks/use-planning-bootstrap-state";
import { usePlanningCommandRegistry } from "@/features/planning/hooks/use-planning-command-registry";
import { usePlanningDerivedState } from "@/features/planning/hooks/use-planning-derived-state";
import { usePlanningTaskSelection } from "@/features/planning/hooks/use-planning-task-selection";
import { useTaskDetailDataLoader } from "@/features/tasks/hooks/use-task-detail-data-loader";

type PlanningAppControllerOptions = PlanningBootstrapStateOptions;

export function usePlanningAppController({
  initialData,
  initialHeaderData,
  initialWorkspace,
  source,
  authRequired,
  demoSeedImportAvailable = false,
  initialAuthUser = null,
  initialCurrentProfile = null,
  initialProtectedDataLoaded = false,
  initialAuthError = "",
  initialReviewTaskId = "",
}: PlanningAppControllerOptions) {
  const router = useRouter();
  const sidebarRef = useRef<HTMLElement | null>(null);
  const bootstrap = usePlanningBootstrapState({
    initialData,
    initialHeaderData,
    initialWorkspace,
    source,
    authRequired,
    demoSeedImportAvailable,
    initialAuthUser,
    initialCurrentProfile,
    initialProtectedDataLoaded,
    initialAuthError,
    initialReviewTaskId,
  });
  const {
    actualProfile,
    apiClient,
    applyPlanningDataUpdate,
    authAvailable,
    authBusy,
    authChecked,
    authError,
    authNotice,
    authUser,
    canChangeTaskStatus,
    canManageFinalTaskStatus,
    canManageTaskMeta,
    canUseCeoIntake,
    currentProfile,
    currentProfileId,
    data,
    devProfileId,
    devRoleSwitchAvailable,
    filters,
    hasPlanningFilterUrlState,
    focusedReviewTaskId,
    githubConnectionState,
    githubInstallationAvailable,
    githubUserConnected,
    waitingGitHubCommentCount,
    githubReauthFailed,
    githubSyncQueueOpen,
    headerData,
    isPending,
    initiativeDialogDefaults,
    localStateLoaded,
    mobileNavOpen,
    protectedDataLoaded,
    refreshPlanningData,
    saveError,
    selectedReviewDetailTaskId,
    selectedTaskId,
    setData,
    setDevProfileId,
    setFilters,
    setFocusedReviewTaskId,
    setGithubSyncQueueOpen,
    setHeaderData,
    setInitiativeDialogDefaults,
    setMobileNavOpen,
    setSaveError,
    setSelectedTaskId,
    setShowFilters,
    setShowNotifications,
    setSprintPlanningOptions,
    setStatusGuardNotice,
    setStatusGuardTaskId,
    setTaskDialogDefaults,
    setView,
    setWorkspace,
    showFilters,
    showNotifications,
    signIn,
    signOut,
    sprintPlanningOptions,
    startTransition,
    statusGuardNotice,
    statusGuardTaskId,
    taskDialogDefaults,
    view,
    workspace,
  } = bootstrap;

  const commandContext = {
    apiClient,
    applyPlanningDataUpdate,
    canChangeTaskStatus,
    canManageFinalTaskStatus,
    canManageTaskMeta,
    currentProfile,
    data,
    githubInstallationAvailable,
    githubUserConnected,
    setData,
    setSaveError,
    source,
    startTransition,
  };

  const taskSelection = usePlanningTaskSelection({
    data,
    router,
    selectedReviewDetailTaskId,
    selectedTaskId,
    setFocusedReviewTaskId,
    setSelectedTaskId,
  });
  const {
    backTaskPanel,
    closeTaskPanel,
    openReviewSheet,
    openTaskPanel,
    selectedTask,
  } = taskSelection;
  const taskDetailDataLoader = useTaskDetailDataLoader({
    apiClient,
    applyPlanningDataUpdate,
    selectedTask,
    source,
    startTransition,
  });

  const derivedState = usePlanningDerivedState({
    authChecked,
    canUseCeoIntake,
    currentProfile,
    data,
    filters,
    setInitiativeDialogDefaults,
    setTaskDialogDefaults,
    setWorkspace,
    statusGuardTaskId,
    workspace,
  });
  const commandRegistry = usePlanningCommandRegistry({
    apiClient,
    closeTaskPanel,
    commandContext,
    currentProfileId,
    data,
    hasPlanningFilterUrlState,
    openTaskPanel,
    refreshPlanningData,
    selectedTask,
    setFilters,
    setHeaderData,
    setInitiativeDialogDefaults,
    setShowNotifications,
    setStatusGuardNotice,
    setStatusGuardTaskId,
    setTaskDialogDefaults,
    setView,
    setWorkspace,
    source,
    sprintPlanningOptions,
    workspace,
  });
  const { boardState, demoSeedImport } = commandRegistry;
  const { demoSeedImportPending, importDemoSeed } = demoSeedImport;

  const releaseSidebarFocus = () => {
    const activeElement = document.activeElement;
    if (activeElement instanceof HTMLElement && sidebarRef.current?.contains(activeElement)) {
      activeElement.blur();
    }
  };

  return {
    actualProfile,
    authAvailable,
    authBusy,
    authChecked,
    authError,
    authNotice,
    authUser,
    canChangeTaskStatus,
    canManageFinalTaskStatus,
    canManageTaskMeta,
    canUseCeoIntake,
    backTaskPanel,
    closeTaskPanel,
    currentProfile,
    data,
    demoSeedImportAvailable: source === "seed" && demoSeedImportAvailable && data.tasks.length === 0,
    demoSeedImportPending,
    devProfileId,
    devRoleSwitchAvailable,
    filters,
    filtersAvailable: derivedState.filtersAvailable,
    focusedReviewTaskId,
    githubConnectionState,
    githubInstallationAvailable,
    githubUserConnected,
    waitingGitHubCommentCount,
    githubReauthFailed,
    githubSyncQueueOpen,
    headerData,
    headerPrimaryAction: derivedState.headerPrimaryAction,
    initiativeDialogDefaults,
    importDemoSeed,
    isPending,
    localStateLoaded,
    metrics: derivedState.metrics,
    mobileNavOpen,
    openReviewSheet,
    openTaskPanel,
    protectedDataLoaded,
    refreshPlanningData,
    releaseSidebarFocus,
    apiClient,
    saveError,
    selectedPackage: taskSelection.selectedPackage,
    selectedReviewDetailTask: taskSelection.selectedReviewDetailTask,
    selectedReviewDetailTaskId,
    selectedTask,
    selectedTaskId,
    selectedTaskActivity: taskSelection.selectedTaskActivity,
    selectedTaskBlockers: taskSelection.selectedTaskBlockers,
    selectedTaskComments: taskSelection.selectedTaskComments,
    selectedTaskDetailError: taskDetailDataLoader.selectedTaskDetailError,
    selectedTaskDetailLoading: taskDetailDataLoader.selectedTaskDetailLoading,
    selectedTaskExternalComments: taskSelection.selectedTaskExternalComments,
    selectedTaskSubIssues: taskSelection.selectedTaskSubIssues,
    taskPanelPreviousTask: taskSelection.taskPanelPreviousTask,
    setData,
    setDevProfileId,
    setFilters,
    setFocusedReviewTaskId,
    setGithubSyncQueueOpen,
    setInitiativeDialogDefaults,
    setMobileNavOpen,
    setShowFilters,
    setShowNotifications,
    setSprintPlanningOptions,
    setStatusGuardNotice,
    setStatusGuardTaskId,
    setTaskDialogDefaults,
    setView,
    showFilters,
    showNotifications,
    sidebarRef,
    signIn,
    signOut,
    sprintPlanningOptions,
    source,
    statusGuardNotice,
    statusGuardTask: derivedState.statusGuardTask,
    taskDialogDefaults,
    view,
    visibleTasks: derivedState.visibleTasks,
    workspace,
    setWorkspace,
    ...boardState,
    ...commandRegistry.eventCommands,
    ...commandRegistry.fmdToolCommands,
    ...commandRegistry.initiativeCommands,
    ...commandRegistry.notificationCommands,
    ...commandRegistry.ownProfileSettingsCommands,
    ...commandRegistry.profileSettingsCommands,
    ...commandRegistry.reviewCommands,
    ...commandRegistry.sprintCommands,
    ...commandRegistry.weeklyAttendanceCommands,
    ...commandRegistry.taskCollaborationCommands,
    ...commandRegistry.taskMutationCommands,
  };
}

export type PlanningAppController = ReturnType<typeof usePlanningAppController>;
