import type { PlanningShellState } from "@/lib/types";

// Client-only composition state for the legacy shell. Never expose it from a server read interface.
export const emptyPlanningShellState: PlanningShellState = {
  project: {
    id: "findmydoc-founder-execution",
    name: "findmydoc Planning",
    range: "Geschützter Teamzugriff",
    reviewObjectionWindowHours: 48,
    githubProjectOwner: "findmydoc-platform",
    githubProjectNumber: 21,
  },
  profiles: [],
  packages: [],
  milestones: [],
  tasks: [],
  sprints: [],
  sprintCommitments: [],
  founderSprintScores: [],
  founderStrikeStates: [],
  strikeEvents: [],
  scoreObjections: [],
  taskComments: [],
  taskExternalComments: [],
  taskBlockers: [],
  taskRelations: [],
  taskActivity: [],
  taskReviews: [],
  taskFocusItems: [],
  notificationEvents: [],
  notificationDeliveries: [],
  notificationPreferences: [],
  profileUiPreferences: [],
  profileFeatureTourAcknowledgements: [],
  fmdTools: [],
  events: [],
  meetings: [],
  meetingAttendance: [],
  audit: [],
};
