create table public.team_workweek_versions (
  id uuid primary key default gen_random_uuid(),
  owner_profile_id text not null references public.profiles(id) on delete cascade,
  effective_from date not null,
  timezone text not null default 'Europe/Berlin',
  status text not null default 'preparing',
  created_at timestamptz not null default now(),
  constraint team_workweek_versions_monday_start
    check (extract(isodow from effective_from) = 1),
  constraint team_workweek_versions_timezone_fixed
    check (timezone = 'Europe/Berlin'),
  constraint team_workweek_versions_private_status
    check (status = 'preparing')
);

create table public.team_workweek_windows (
  id bigint generated by default as identity primary key,
  version_id uuid not null references public.team_workweek_versions(id) on delete cascade,
  weekday smallint not null,
  start_minute smallint not null,
  end_minute smallint not null,
  constraint team_workweek_windows_weekday_range
    check (weekday between 1 and 7),
  constraint team_workweek_windows_time_range
    check (start_minute between 0 and 1438 and end_minute between 1 and 1439 and start_minute < end_minute)
);

create index team_workweek_versions_owner_created_idx
  on public.team_workweek_versions (owner_profile_id, created_at desc, id desc);

create index team_workweek_windows_version_day_idx
  on public.team_workweek_windows (version_id, weekday, start_minute, end_minute);

comment on table public.team_workweek_versions is
  'Immutable private FounderOps team-workweek versions. Publication is modeled separately and never mutates these drafts.';

comment on table public.team_workweek_windows is
  'Europe/Berlin wall-clock windows belonging to one immutable private team-workweek version.';

alter table public.team_workweek_versions enable row level security;
alter table public.team_workweek_windows enable row level security;

create policy team_workweek_versions_select_owner_private
  on public.team_workweek_versions
  for select
  to authenticated
  using (
    owner_profile_id = public.current_profile_id()
    and public.current_platform_role() in ('ceo', 'founder', 'deputy')
  );

create policy team_workweek_windows_select_owner_private
  on public.team_workweek_windows
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.team_workweek_versions as version
      where version.id = team_workweek_windows.version_id
        and version.owner_profile_id = public.current_profile_id()
        and public.current_platform_role() in ('ceo', 'founder', 'deputy')
    )
  );

revoke all on table public.team_workweek_versions from public, anon, authenticated, service_role;
revoke all on table public.team_workweek_windows from public, anon, authenticated, service_role;
revoke all on sequence public.team_workweek_windows_id_seq from public, anon, authenticated, service_role;
grant select on table public.team_workweek_versions to authenticated;
grant select on table public.team_workweek_windows to authenticated;
grant select on table public.team_workweek_versions to service_role;
grant select on table public.team_workweek_windows to service_role;

create or replace function public.create_private_team_workweek_version(
  p_effective_from date,
  p_windows jsonb
) returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_owner_profile_id text;
  v_owner_role text;
  v_today date := (clock_timestamp() at time zone 'Europe/Berlin')::date;
  v_next_monday date;
  v_version_id uuid;
  v_window jsonb;
  v_weekday smallint;
  v_start_minute smallint;
  v_end_minute smallint;
begin
  v_next_monday := v_today + case
    when extract(isodow from v_today)::integer = 1 then 7
    else 8 - extract(isodow from v_today)::integer
  end;

  select profile.id, profile.platform_role
  into v_owner_profile_id, v_owner_role
  from public.profiles as profile
  where profile.auth_user_id = auth.uid();

  if not found or v_owner_profile_id is null then
    raise exception using errcode = '42501', message = 'mapped team profile required';
  end if;
  if v_owner_role not in ('ceo', 'founder', 'deputy') then
    raise exception using errcode = '42501', message = 'viewer cannot create a private team workweek';
  end if;
  if p_effective_from is null
    or extract(isodow from p_effective_from)::integer <> 1
    or p_effective_from < v_next_monday then
    raise exception using errcode = '22023', message = 'effective date must be a future Monday';
  end if;
  if p_windows is null or jsonb_typeof(p_windows) <> 'array' or jsonb_array_length(p_windows) > 84 then
    raise exception using errcode = '22023', message = 'workweek windows must be a bounded array';
  end if;

  insert into public.team_workweek_versions (owner_profile_id, effective_from)
  values (v_owner_profile_id, p_effective_from)
  returning id into v_version_id;

  for v_window in select value from jsonb_array_elements(p_windows)
  loop
    if jsonb_typeof(v_window) <> 'object'
      or exists (
        select 1
        from jsonb_object_keys(v_window) as key
        where key not in ('weekday', 'startMinute', 'endMinute')
      )
      or v_window->>'weekday' is null
      or v_window->>'startMinute' is null
      or v_window->>'endMinute' is null then
      raise exception using errcode = '22023', message = 'workweek window contains unsupported fields';
    end if;

    begin
      v_weekday := (v_window->>'weekday')::smallint;
      v_start_minute := (v_window->>'startMinute')::smallint;
      v_end_minute := (v_window->>'endMinute')::smallint;
    exception when invalid_text_representation or numeric_value_out_of_range then
      raise exception using errcode = '22023', message = 'workweek window contains invalid values';
    end;

    if v_weekday not between 1 and 7
      or v_start_minute not between 0 and 1438
      or v_end_minute not between 1 and 1439
      or v_start_minute >= v_end_minute then
      raise exception using errcode = '22023', message = 'workweek window must stay inside one day and begin before it ends';
    end if;
    if (
      select count(*)
      from public.team_workweek_windows as existing
      where existing.version_id = v_version_id
        and existing.weekday = v_weekday
    ) >= 12 then
      raise exception using errcode = '22023', message = 'workweek day contains too many windows';
    end if;
    if exists (
      select 1
      from public.team_workweek_windows as existing
      where existing.version_id = v_version_id
        and existing.weekday = v_weekday
        and v_start_minute < existing.end_minute
        and v_end_minute > existing.start_minute
    ) then
      raise exception using errcode = '22023', message = 'workweek windows must not overlap';
    end if;

    insert into public.team_workweek_windows (version_id, weekday, start_minute, end_minute)
    values (v_version_id, v_weekday, v_start_minute, v_end_minute);
  end loop;

  return jsonb_build_object(
    'id', v_version_id,
    'effectiveFrom', p_effective_from,
    'timezone', 'Europe/Berlin',
    'status', 'preparing',
    'createdAt', clock_timestamp()
  );
end;
$$;

alter function public.create_private_team_workweek_version(date, jsonb) owner to postgres;
revoke all on function public.create_private_team_workweek_version(date, jsonb) from public, anon, service_role;
grant execute on function public.create_private_team_workweek_version(date, jsonb) to authenticated;
